### ISSUE TITLE
Update code for JEDI

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3247] opened 2023-01-04 17:31 UTC
Title of ticket: 

#### Description
Summarize issue 

Change org code from JERI to JEDI

#### Dependencies
Are there any dependencies?

Yes, need new org code setup in AXIS.

Need to update code in TEST AXIS. Assumption they add a new code as the old code still runs for inflight requests.

#### DOD
- [x] Update org code in FOI Mod

**Comment by lmullane** [comment] 2023-01-04 17:43
Old code will be used for inflight requests. Dashboard will need two codes and will need to pull both ministries for historical data.

**Comment by abin-aot** [comment] 2023-01-06 00:10
@lmullane , Moving reporting dashboard task to existing Reporting Dashboard task #3192, #3194 . it is easier to handle all together

**Comment by abin-aot** [comment] 2023-01-06 00:20
@lmullane , @m-prodan : I am proceeding with JED since on AXIS DEV, TEST its JED , not JEDI

**Comment by abin-aot** [comment] 2023-01-06 18:27
New Ministry KC group . This group will have same users as of JERI in PROD. @lmullane  , @m-prodan 
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/8058ece6-a518-4094-98b1-126d0244f206)

**Comment by KyEggleston** [comment] 2023-01-06 19:26
Confirmed org code and 'Ministry Assigned To' updated in FOI Mod.

Confirmed ministry name updated in Angular app. 

Closing ticket.

**Closed** 2023-01-06 19:26 UTC
Labels: Task, onboarding

**Comment by abin-aot** [comment] 2023-01-11 00:35
PROD RELEASE STEPS Taken
1. Created DB back up of Camunda, FOI DB
	-  patroni-master-002-ffa-camunda_2023-01-10_15-41-16.sql.gz  
	- patroni-master-002-foidb_2023-01-10_15-41-15.sql.gz 
2. Backed images FormsFlowWeb and Requestmanagement api -002
	- oc tag forms-flow-web:prod forms-flow-web:prod-bu
        - oc tag request-management-api:prod-002 request-management-api:prod-002-bu

2. Tagging FormsFlowWeb and Request Managment API - 002
	- oc tag  request-management-api:test request-management-api:prod-002
	- oc tag  forms-flow-web:test forms-flow-web:prod
