### ISSUE TITLE
Advanced Search - Front End

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/foi-flow#1461] opened 2022-02-08 16:18 UTC

**Comment by JHarrietha-AOT** [comment] 2022-02-09 19:31
@jadmsaadaot @amichard Here are the updated designs for the advanced search, let me know if you have any questions

https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874445058

**Comment by lmullane** [comment] 2022-02-15 23:43
@JHarrietha-AOT , @jadmsaadaot, is this a duplicate of #1213?

**Comment by lmullane** [comment] 2022-02-16 00:07
Resolved with @abin-aot. This is a task for #1213

**Closed** 2022-02-18 01:54 UTC
