### ISSUE TITLE
Advanced Search - Received date with Unopened State is not working as expected

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#2192] opened 2022-05-19 00:03 UTC
**Describe the bug in current situation**
Advanced Search - Received date with Unopened State is not working as expected in training.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Training env

**Steps to Reproduce**
1. Submit request from request form (Online), Today business hour
2. Go to Advanced Search
3. Click on Received Date
4. Select From and To as May 18th, 2022 (Today)
5. Select Status "Unopened"

**Actual/ observed behaviour/ results**
The list not showing. But if you type To Date as future date (Tomorrow) then the list shows. 

**Expected behaviour**
The list should show based on the filter

**Screenshots/ Visual Reference/ Source**
Total unopened requests in Training.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/4574e9f7-f6c5-4e32-8194-dd1874925152)

Actual issue
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/df16a771-9a81-491e-afdb-0c0165a5aa04)

Future Date then List shows
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/5a440044-6326-4f4e-84da-552dc10c397a)

**Comment by lmullane** [comment] 2022-06-20 18:49
@sumathi-thirumani-aot, please try to replicate. May be a time zone issue.

**Comment by richard-aot** [comment] 2022-06-22 23:51
#2185, #2192 and #2308 are the same issue

**Comment by lmullane** [comment] 2022-06-28 17:36
Duplicate of #2185

**Closed by lmullane** 2022-06-28 17:36 UTC
Labels: bug
