### ISSUE TITLE
On Hold - Countdown Timer - Stat Holiday

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#864] opened 2021-11-15 17:28 UTC
**Describe the bug in current situation**
When a request goes on hold over a stat holiday, it appears to give the CFR and LDD countdown an extra day.

The due date has recalculated correctly, but the days remaining shown is wrong. 

**Link bug to the User Story** #685

**Impact of this bug**
Visual bug - LDD is recalculated correctly, countdown timers displaying incorrect days remaining

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Place a request on hold ahead of a stat holiday
2. Take request off hold after stat holiday passes, on next business day
3. Check due date and countdowns

**Actual/ observed behaviour/ results**

**Expected behaviour**
Due date has recalculated properly, but the countdown timers on the left hand panel give an extra day

**Screenshots/ Visual Reference/ Source**

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/ff46a156-1e06-45be-820b-e4b14fea1ac7)

**Comment by mpilchar** [comment] 2021-12-17 21:33
@arielleandrews @m-prodan Discuss if we can close this, technically it's correct because it includes the start and end date in the count (days counting is inclusive)

**Comment by arielleandrews** [comment] 2021-12-20 19:24
Discussed with @m-prodan and agreed the behaviour is as expected and not a bug.

**Closed by arielleandrews** 2021-12-20 19:24 UTC
Labels: bug
