### ISSUE TITLE
Order of Extension list is incorrect

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#1505] opened 2022-02-15 19:34 UTC
**Describe the bug in current situation**
Extension list should show based on the state. Pending, Approved and Denied

**Link bug to the User Story**
#878

**Impact of this bug**
Order of Extension list is incorrect

**Chance of Occurring (high/medium/low/very low)**
high

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
all env

**Steps to Reproduce**
1. Go to any Open request
2. Click on add extension
3. Add an OIPC approved extension
4. Add another OIPC denied extension
5. Add another OIPC pending extension

**Actual/ observed behaviour/ results**
OIPC denied extension shows in the top

**Expected behaviour**
OIPC Pending extension should show in the top. Followed by Approved and Denied

**Screenshots/ Visual Reference/ Source**
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/ca9ae8ff-797e-4732-bcbe-09c91534eba7)If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by nkan-aot** [comment] 2022-03-03 18:09
Could not reproduce, tested in local and dev:
![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/62039734-cdab-4157-bc28-24a0abc33d14)

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/589839f4-9440-4d61-9228-f13fac90217d)

**Comment by nkan-aot** [comment] 2022-05-12 17:16
reopening since denied should be below approved

**Comment by KaraBeach** [comment] 2022-05-17 17:24
@nkan-aot , are the extensions suppose to be in order of entry or grouped by status? Example: EDU-2022-00086 I took an extension prior to following the instructions in this ticket (PB extension) It is now showing 3rd in the list. Should it be at the bottom- due to being entered first? Otherwise, I followed the steps to reproduce.

**Comment by KaraBeach** [comment] 2022-05-17 23:36
@nkan-aot  Matt clarified the ticket for me and confirmed that they are grouped by status with pending on top ( only one allowed) followed by approved, and then denied. Closing the ticket.

**Closed by KaraBeach** 2022-05-17 23:36 UTC
Labels: bug, medium priority

**Comment by nkan-aot** [comment] 2022-05-17 23:40
@KaraBeach hey sorry didn't see your comment from this morning, thanks for confirming and QAing the ticket!
