### ISSUE TITLE
Sync with AXIS an already added request

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1540] opened 2022-02-18 00:04 UTC
* As an IAO analyst
* I want to be able to sync with AXIS for a request that has already been added to the new system
* so that I can save time on data entry between the two systems

**Assumptions & Scope**	
What are the assumptions for this story?

Sync will overwrite request details in the new system with information from AXIS.

Sync will only appear on the IAO request view, not the ministry coordinator request view.

What is IN scope?
Ongoing syncing data from AXIS into the new system when a request has already been added to the new system and synced once from AXIS.

Syncing will only update: 

- Extensions
- LDD
- Applicant Details (including child)
- Contact Information (from applicant profile)
- Request Description
- Date Ranges
- Request Details (i.e. dates)

What is NOT in scope?

- Adding a new request, which is covered in #1535 
- Changing the state of a request.
- Ministry coordinators ability to sync.
- Assigned to and watchers.
- Comments
- Attachments

**Acceptance Criteria**	

**Scenario 1: 'Sync to AXIS' button**
* GIVEN an IAO analyst is on a queue
* WHEN the analyst clicks on a request in any request state
* THEN the analyst will be redirected to the request view
* AND there will be a button 'Sync to AXIS' next to the 'Save' button at the bottom of the request
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Scenario 2: Click 'Sync to AXIS - open modal'**
* GIVEN an IAO analyst is on a request view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* WHEN the analyst clicks the 'Sync to AXIS' button
* THEN a modal will open asking "Are you sure you want to sync? Syncing will update the request details with the information with details from AXIS"
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* AND there will be buttons to 'Save Changes' (primary), Cancel (secondary)
* AND an accordion to see 'Review Changes in AXIS'

**Scenario 3: Cancel Sync**
* GIVEN an IAO analyst is on the sync modal
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* WHEN the analyst clicks the 'Cancel' button
* THEN a modal will close
* AND the analyst will remain on the request view

**Scenario 4: View Changes in AXIS**
* GIVEN an IAO analyst is on the sync modal
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* WHEN the analyst clicks the 'Review Changes in AXIS'
* THEN accordion on the modal will open
*  https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* AND changes that have been made in AXIS to the request details, extensions and LDD will be displayed in a right column
* AND Field Descriptors for the updated fields will be displayed in a left column for comparison

**Scenario 5: Save Changes **
* GIVEN an IAO analyst is on a request view
* https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852
* WHEN the analyst clicks the 'Save Changes' button
* THEN the changes made in AXIS will now be saved in the request
* AND the modal will close
* AND the user will remain on the request view
* AND a green toast will be briefly appear with a success message: "The request has been saved successfully"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/812308852

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2022-02-19 01:07
@abin-aot, @sumathi-thirumani-aot, @m-prodan 

I have updated the AC as discussed this morning. Rather than 2 modals the changes in AXIS can be viewed by opening an accordion on the one modal. Please review.

Do we need a scenario to close the accordion?

cc @arielleandrews. @JHarrietha-AOT, @mpilchar

**Comment by JHarrietha-AOT** [comment] 2022-02-23 17:23
@abin-aot @lmullane Here is a link to the updated designs with the sync changes captured in an accordion. Let me know if you have any questions or need any further design changes.

 https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/874891784

cc: @m-prodan @arielleandrews

**Comment by m-prodan** [comment] 2022-02-23 17:42
I believe this is the story we should add an AC to ensure extensions trigger a notification (shouldn't require additional work, but need to ensure it works as expected)

**Comment by divyav-aot** [comment] 2022-03-25 19:09
@m-prodan - as we discussed, in this story we are not fetching CFR DUE DATE from AXIS. We will tackle that in a separate task.
AXIS has multiple CFR DUE DATE per request. We will fetch the latest CFR DUE DATE for the OFFICEID(EDU, LBR etc). Please confirm.
@abin-aot  @VineetBala-AOT

**Comment by m-prodan** [comment] 2022-03-25 19:37
Confirmed - thanks Divya

**Comment by lmullane** [comment] 2022-04-01 21:53
@divyav-aot, one question. For changes to the applicants address information are those only synced from the applicant profile in AXIS?

In other words we do not sync from the request billing or shipping addresses listed on the request?

**Comment by divyav-aot** [comment] 2022-04-01 22:16
@lmullane yes that is correct. We take the address information from applicant profile.

**Comment by lmullane** [comment] 2022-04-02 03:15
Cool, thanks for the confirmation, @divyav-aot

**Comment by lmullane** [comment] 2022-04-07 23:02
@m-prodan, couple of things I've not been able to successfully sync:

1. Under request details I was not able to sync the change of a request type from 'General' to 'Personal
2. I was not able to sync 'On Behalf of' to a personal request

@m-prodan , do you think analysts will need to change the request type?

cc @divyav-aot 

I will write these up as bug tickets.

**Comment by lmullane** [comment] 2022-04-08 16:34
Confirmed request type cannot be changed after open in our system. It is very rare that this needs to be done.

**Comment by m-prodan** [comment] 2022-04-08 22:27
@lmullane - I think I have found the same issue as you around 'On Behalf Of'

When I first add a request, that has an On Behalf Of included in it, and I do the initial sync - I can confirm that the on behalf of DOES get synced.

If the On-behalf-of is updated in AXIS; however, the banner will not appear and subsequent syncs do not pull the updated OBO.

Everything else seems to work though - there is the issue we found with the extensions, but it technically meets the AC, because the way the analysts fix it in AXIS won't lend itself well to our sync, so I think that may need to be addressed with a seperate UX/Story.

I would feel ok about closing this one having done a bunch of different syncs at this point in time... but let me know your thoughts on how you want to handle the OBO issue.

**Comment by aparna-aot** [comment] 2022-04-08 22:54
@m-prodan @lmullane We were able to reproduce the issue with On -Behalf-of. I'm currently looking into it. You can create a separate bug ticket for it and close this one. And I will add my updates to the new ticket.

**Comment by m-prodan** [comment] 2022-04-11 15:53
Hi team - @aparna-aot @divyav-aot  @lmullane 

While I was doing another test, I had something happen that I haven't seen before. Extensions now appear to be overwriting the prior when I sync. As an example, IAO-2022-00216 - has 3 extensions in AXIS, but only the latest one is showing in the extension log. This wasn't happening before, so I wonder if a change was pushed recently that might have triggered this? will flag at stand up.

**Comment by divyav-aot** [comment] 2022-04-11 17:12
@m-prodan this issue is fixed. you should be able to see 3 extensions now. 
Currently, all extensions will be replaced with AXIS extensions whenever a sync happens.

**Comment by m-prodan** [comment] 2022-04-11 23:21
Confirmed that the file I attempted the sync with originally, now pulls all 3 extensions and displays them as expected.

@lmullane - should we close this one now? We can handle the OBO bug separately perhaps?

**Comment by lmullane** [comment] 2022-04-11 23:24
@m-prodan, I'm just finishing up on the testing now. I will write the OBO bug separately.

**Closed** 2022-04-12 14:15 UTC
Labels: Story
