### ISSUE TITLE
Change State from Deduplication to Harms Assessment

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#688] opened 2021-10-15 23:14 UTC
* As an IAO analyst
* I want to be able to change the state of a request to Harms Assessment 
* so that I know deduplication is complete and that the Ministry is responsible for the next state of the request 

**Assumptions & Scope**	
* Deduplication is a sub-state of Call for Records
* Only an IAO analyst can change the state from Deduplication to Harms Assessment

What is IN scope?
* Reflecting the state change in IAO and Ministry queues

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: IAO Analyst 'Deduplication' dropdown menu**
* GIVEN I am an IAO analyst
* WHEN the state of the request is in 'Deduplication' state 
* AND I have clicked on the state dropdown menu
* THEN the options will be 'Harms Assessment', 'Review', and 'Closed' 

**Scenario 2: Select 'Harms Assessment' in dropdown menu**
* GIVEN the Ministry user has clicked the state dropdown menu
* WHEN I click on 'Harms Assessment' from the dropdown menu 
* THEN a modal will open with the options to 'Save Change' or 'Cancel'
* AND the IAO assignee and the ministry assignee will display in the modal 

**Scenario 3: Cancel change to 'Harms Assessment'**
* GIVEN the IAO analyst has opened the modal for 'Harms Assessment'
* WHEN I select 'Cancel' in the modal
* THEN the state of the request will remain 'Deduplication'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue in 'Deduplication' state

**Scenario 4: Save change to 'Harms Assessment'**
* GIVEN the IAO analyst has opened to modal for 'Harms Assessment'
* WHEN I select 'Save Change' in the modal
* THEN the state of the request will become 'Harms Assessment'
* AND the dropdown menu and modal will close
* AND the request will remain in the IAO and Ministry queue but now in 'Harms Assessment' state

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2021-11-03 21:58
Duplicate of #765

**Closed** 2021-11-03 21:58 UTC
Labels: Story
