### ISSUE TITLE
Sync Modal lists already saved Extensions

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1879] opened 2022-04-12 07:16 UTC
**Describe the bug in current situation**

GIVEN a user has already saved (i.e., synced) the extension(s) to the request
AND the user adds another extension in AXIS 
AND the user clicks the sync button
WHEN the user clicks the 'Review Changes from AXIS'
THEN the user will see the new extension listed
AND the user will see the already synced extensions listed

![Screen Shot 2022-04-11 at 9.08.14 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/75542f77-fd45-4e9d-8dc1-082d895622bf)

**Link bug to the User Story**
#1540 

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

Low.  Confusing for the user, but does the stale extensions listed are not saved again to the request.
**Chance of Occurring (high/medium/low/very low)**

Unknown

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request in AXiS
2. Add an extension
3. Go to the same request in Flow
4. Click the Sync button
5. Click 'Review Changes from AXIS' in the sync modal
6. Click 'Save Changes'
6. See the extension added to the request
6. Add another extension in AXIS
7.Click the Sync button
5. Click 'Review Changes from AXIS' in the sync modal
6. See the new Extension listed 
7. See the previous stale extension still listed.
8. Click 'Save Change'
9. See that only the new extension is added to the request (i.e. the stale extensions are not duplicated)

**Actual/ observed behaviour/ results**

**Expected behaviour**
GIVEN an extension or any synced data has already been saved to a request
WHEN the user syncs new data
AND clicks 'Review Changes from AXIS' in the sync modal
THEN the previously synced extensions will no longer be listed
AND only the new extension will appear

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by m-prodan** [comment] 2022-04-14 16:22
Hi @aparna-aot - looks good to me!

**Comment by m-prodan** [comment] 2022-04-22 22:51
Thanks @aparna-aot - the issue appears to be correct, and I like the addition of the red text when our app has an extension but AXIS does not.

One thing I noticed, and I'm not sure if its because of the RFD issue - but it seems the sync is now still pulling extensions, but its just showing a blank field: 

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/de07eeef-94a6-4a1d-a62e-df732df95850)

It has no impact on the extension log or LDD - but it might be confusing for users. Given that, I am going to put this back in review to see if we can fix that little piece

**Comment by m-prodan** [comment] 2022-04-22 22:57
Update - this issue will be fixed when #1905 goes to TEST - adding a dependency to this. This should be retested when 1905 is released to test

**Comment by m-prodan** [comment] 2022-04-29 23:56
Confirmed fixed with #1905 - nice work @aparna-aot !

**Closed by m-prodan** 2022-04-29 23:56 UTC
Labels: bug
