### ISSUE TITLE
Document Reviewer - Review Layers

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3717] opened 2023-04-27 15:27 UTC
* As an IAO user
* I want to be able to switch my view to the various layers I may need to work with
* so that I can view the product and make adjustments as necessary

**Assumptions & Scope**	
This story reflects the need for IAO users, while working in the redaction tool, to be able to change layers depending on the specific need/situation.

For definitions - the review layers mean as follows:
Redline = View of records showing annotated redactions (eg - redlined information, records are NOT redacted), and comments for the Ministry user
IAO Review = View of records showing annotated redactions (eg - redlined information, records are NOT redacted), and comments for the Ministry user, and comments/markups internally for IAO
Harms = marked up copy provided by Ministry reviewer (NOTE: this will not be in scope for this release)
Ministry Sign-Off = Redline version showing comments and annotations from Ministry sign-off reviewers (NOTE: this will not be in scope for this release)
Records Package = the redacted copy of the records, with no comments - all proposed redactions have been applied to the pages.

Open Info Layer, OIPC Layer = Separate stories for definitions and scope will be created at a later date

What is IN scope?
Creating/switching to layers showing the Records Package, the Redline, and IAO Review

What is NOT in scope?
Layers for harms, Ministry sign off, Open Info, and OIPC Layer. 

**Design**
https://jacklyn808742.invisionapp.com/console/Redaction-cla8feezv003o015h7op82c5c/cleg4xqe55wt3018ba31e3cvi/play

**Acceptance Criteria**	

**Scenario 1: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 2: xxxxxx**
* GIVEN ... (you or your condition)
* WHEN ... (what you do) 
* THEN ... (what you see) 

**Scenario 3: xxxxxx**
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2023-06-30 18:44
Appears this is a duplicate of #3097

**Comment by lmullane** [comment] 2023-07-06 17:56
Duplicate

**Closed by lmullane** 2023-07-06 17:56 UTC
Labels: Story
