### ISSUE TITLE
Determine tool for automated testing

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#286] opened 2021-08-03 21:15 UTC
#### Description
Determine tool for automated testing

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Look into a licence - cost vs time savings
- [ ] Discuss with team
- [ ] Determine this sprint what best go-forward option is
- [ ] Implement
- [ ]

**Comment by lmullane** [comment] 2021-11-24 17:56
Duplicate of #444

**Closed by lmullane** 2021-11-24 17:56 UTC
Labels: Task
