### ISSUE TITLE
PROD - LDD Recalculating Incorrectly After On-Hold (need to reproduce)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4697] opened 2023-11-06 16:21 UTC
**Describe the bug in current situation**
User report on HTH-2023-32396 - applicant paid fee, but confirmation email to applicant suggested new LDD would be over a year away, which is incorrect.

Request appeared to be on hold the entire team, with a round of narrowing and a revised fee estimate that was paid.

**NEED TO REPRODUCE**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment] 2023-11-09 18:10
Duplicate of #4702

**Closed** 2023-11-09 18:10 UTC
Labels: bug, production
