### ISSUE TITLE
Redaction box is not drawing at the right place

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4570] opened 2023-10-06 19:18 UTC
**Describe the bug in current situation**
Navigate to a page (pagenumber 15 or more than that) from the left panel. Try to draw the redaction box. It is not drawing at the expected place.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to doc reviewer
2. Click on any page > 15
3. try to draw redaction box

**Actual/ observed behaviour/ results**
Redaction box is not drawing at the expected place.
**Expected behaviour**
Redaction box should drawing at the expected place.

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01UQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--294590f3bb54ebb6fcd28f357df3eadfca2cf399/drawingredaction_issue.mp4)

**Comment by m-prodan** [comment] 2023-10-06 20:05
@divyav-aot - does this happen on any record type after page 15, or just excel? Either way, agree this is a high priority!

**Comment by divyav-aot** [comment] 2023-10-06 21:46
@m-prodan, I tired for excel and pdf. both were having this issue.

**Comment by milosdes** [comment] 2023-10-11 17:48
@divyav-aot figured out that the issue is connected to zooming in docreviewer. Certain zoom % will have the issue, other zoom % it will be fine.

**Comment by divyav-aot** [comment] 2023-10-11 18:44
Created the apryse ticket for this issue.
https://support.apryse.com/support/tickets/63510

**Comment by KyEggleston** [comment] 2023-10-12 16:48
Investigate along with #4586 to see if both related to same zoom feature / Apryse issue, and update ticket with Apryse accordingly.

**Comment by divyav-aot** [comment] 2023-10-16 19:13
As discussed, we are keeping this as a known issue. workaround is to make the zoom level to "fit to page" or >200% to draw the redaction boxes.
cc. @abin-aot @lmullane @m-prodan @KyEggleston @nkan-aot

**Comment by abin-aot** [comment] 2023-10-31 21:09
Seems to be working with Apryse 10.5 version, will be available to test-marshal soon

**Comment by nimya-aot** [comment] 2023-11-03 16:00
working as expected, so closing

**Closed by nimya-aot** 2023-11-03 16:00 UTC
Labels: bug, high priority, Vendor
