### ISSUE TITLE
Public Facing Wording Fixes - Fees

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3149] opened 2022-12-05 17:57 UTC
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/d5b96785-2c4b-473f-bd23-f0e516dfacec)
- [x] Process Payment Landing Page (See above) - update language to "If you would like to contact an Information Access Operations representative for assistance, and/or to better clarify your request to try and reduce or eliminate your fee, please contact us by email at: FOI.Requests@gov.bc.ca, or call 250-387-1321 | Toll Free 1-833-283-8200 

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/af03cc36-b417-4c01-b7c0-81c421a98fc6)
- [x] Fee Estimate Landing Page (see above) - update message to: If you need additional assistance or want other payment options, please contact us by email at: FOI.Requests@gov.bc.ca, or call 250-387-1321 | Toll Free 1-833-283-8200

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/03610927-b33a-4bb2-8c49-1a111442f716)
- [x] Deposit Payment Page (See Above) update language to "If you would like to contact an Information Access Operations representative for assistance, and/or to better clarify your request to try and reduce or eliminate your fee, please contact us by email at: FOI.Requests@gov.bc.ca, or call 250-387-1321 | Toll Free 1-833-283-8200 

![image](https://user-images.githubusercontent.com/117312323/206802083-03e3edcf-e9be-4e45-b1b9-051b61f693c7.png)
- [x] Payment Successful Page - update the sentence: "You have received an email regarding your request details and a copy of your receipt" to include a period at the end. 
e.g., _You have received an email regarding your request details and a copy of your receipt._

**Comment by liseandtea** [comment] 2022-12-05 19:03
Minor editing suggestions:

1 and 3) If you would like to contact an Information Access Operations representative for assistance; to better clarify your request to try and reduce or eliminate your fee, please email: FOI.Requests@gov.bc.ca, or call 250-387-1321 | Toll-Free 1-833-283-8200.

2) If you need additional assistance or prefer different payment options, please email: FOI.Requests@gov.bc.ca, or call 250-387-1321 | Toll-Free 1-833-283-8200.

**Comment by KyEggleston** [comment] 2022-12-06 20:23
@liseandtea @m-prodan @lmullane - I checked the updates in this ticket, and see below for details:
<br>
<h3>Payment Processing Landing Page and Deposit Payment Page</h3>

Both the Payment Processing Landing Page and the Deposit Payment Page have been updated to read as the following, which is not identical to Matt's verbiage above:

![image](https://user-images.githubusercontent.com/117312323/206008606-aad59d78-8b21-4e81-8a11-36d248cf40d6.png)

Here is what it would look like with Matt's verbiage, and may need some formatting to not cut off the phone number.

![image](https://user-images.githubusercontent.com/117312323/206008422-eaca9572-50d2-447b-a095-636bd33184b6.png)

Here is what it would look like with Lise's editing suggestions above: 

![image](https://user-images.githubusercontent.com/117312323/206009779-acbb6f59-23de-48a2-b730-b34fbb2fea43.png)

These images only show the Process Payment Landing Page, but the verbiage we want to update is the same as the Deposit Payment Page.
<br>
<h3>Fee Estimate Landing Page</h3>

The Fee Estimate Landing Page has been updates to read as the following, which doesn't exactly match Matt's verbiage:

![image](https://user-images.githubusercontent.com/117312323/206011862-758ac751-be68-449e-b726-759f0e90440a.png)

And here is what it looks like with Matt's verbiage:

![image](https://user-images.githubusercontent.com/117312323/206013096-4adc255e-7589-434b-b0cd-602e14e5ac70.png)

And here is based on Lise's updated verbiage above:

![image](https://user-images.githubusercontent.com/117312323/206013639-5c051fd8-8fc4-4c5e-8762-c2078a706359.png)
<br>
Lots of options for what we want this to read as, and how we want it formatted. Any thoughts? We can chat at a business meeting about it if that's easier too.

**Comment by KyEggleston** [comment] 2022-12-09 21:59
Added one more verbiage update to original comment for the Payment Successful Page.

**Comment by KyEggleston** [comment] 2022-12-12 19:40
@divyav-aot - below are some updates to the language/grammer on the public facing pages for fee payments. Can we make these updates and confirm when they're done? 

<h3>Payment Processing Landing Page</h3>

Update to the following:

![image](https://user-images.githubusercontent.com/117312323/207133743-e42c27a0-e178-4bf3-8e57-52dfc7d36e74.png)

<h3>Fee Estimate Landing Page</h3>

Update to the following:

![image](https://user-images.githubusercontent.com/117312323/207135332-94a9d11c-1ba7-4004-a522-3452c4376356.png)


<h3>Deposit Payment Page</h3>

Update to the following:

![image](https://user-images.githubusercontent.com/117312323/207133743-e42c27a0-e178-4bf3-8e57-52dfc7d36e74.png)

<h3>Payment Successful Page</h3>

Add a period where it is highlighted, update the language (including hyperlinking the email and phone numbers), and remove the custom background-color on the contact information line.  ![image](https://user-images.githubusercontent.com/117312323/207137938-29b065f0-2ce0-4453-9a26-c97de3a0b888.png)

It should look like the following (minus the yellow highlighter):

![image](https://user-images.githubusercontent.com/117312323/207138059-4beb1bbe-d3a5-4938-a20a-82c9ba65932f.png)

Let me know if you have any questions! 

cc: @lmullane

**Comment by divyav-aot** [comment] 2022-12-12 19:45
Thanks @KyEggleston . I will update and let you kow.

**Comment by divyav-aot** [comment] 2022-12-12 20:43
@KyEggleston the changes are pushed to test. could you please test and confirm.

**Comment by KyEggleston** [comment] 2022-12-12 22:10
Thanks @divyav-aot - one small fix left:

On the Payment Processing Landing Page and Deposit Payment page, update "and" to "to".  See below for where the change should happen (highlighted). 
![image](https://user-images.githubusercontent.com/117312323/207165121-6a6ebee4-a484-40d4-a024-5cc277e3180d.png)

After that is updated, I will confirm the update and I think we can close this.

**Comment by divyav-aot** [comment] 2022-12-12 23:01
@KyEggleston updated the text. Please test and confirm.

**Comment by KyEggleston** [comment] 2022-12-12 23:46
Thanks @divyav-aot - I've confirmed all the updates have been made in test. I believe this can be closed @lmullane?

**Comment by lmullane** [comment] 2022-12-12 23:58
Agreed. Closed it.

**Closed by lmullane** 2022-12-12 23:58 UTC
Labels: bug, Task, Fees
