### ISSUE TITLE
Comments on Word/Excel/MS Office docs not appear on PDF conversions

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3981] opened 2023-06-20 23:46 UTC
* As a ministry reviewer and IAO analyst
* I want comments on Word/Excel/Office documents to be visible on converted PDFs
* so that I can flag the comments for harms or redact the comment if needed

**Assumptions & Scope**	
What are the assumptions for this story?

When Word/Excel/MS Office documents that have comments are converted to PDF by Intella, the comments are visible in the converted PDF.

Comments on Word/Excel/MS Office documents are part of the responsive records and should be included in the Records Package.

What is IN scope?
Including comments in Word/Excel/MS Office documents in the converted PDF.

Need to see what Intella produces.

What is NOT in scope?
Including comments in PDFs.

**Acceptance Criteria**	

**Scenario 1: Display comments in converted Word/Excel/MS Office doc**
* GIVEN a Word/Excel/MS Office document has comments
* WHEN the Word doc is uploaded into FOI Mod
* THEN the Word doc will be converted to PDF
* AND the comments will be visible in the PDF
* see Intella example

**Scenario 2: Display replies to comments in converted Word/Excel/MS Office doc**
* GIVEN a Word/Excel/MS Office document has replies to comments
* WHEN the Word doc is uploaded into FOI Mod
* THEN the Word doc will be converted to PDF
* AND the replies to comments will be visible in the PDF
* see Intella example

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2023-06-20 23:48
@m-prodan, we should include this bug/story in the next sprint. Wrote as a story so that it can be added to our regression suite.

**Comment by abin-aot** [comment] 2023-06-21 16:55
DOCX to PDF : https://help.syncfusion.com/file-formats/docio/word-to-pdf#comments-in-word-to-pdf-conversion
XLSX to PDF : https://help.syncfusion.com/file-formats/xlsio/excel-to-pdf-conversion#convert-comments-as-displayed-in-place

**Comment by m-prodan** [comment] 2023-06-22 16:15
Note from standup - ticket raised with syncfusion re: excel - they will have an update to address this, but right now projecting September release. docx may function as intended, so we may split this ticket.

**Comment by divyav-aot** [comment] 2023-06-22 18:56
As discussed, the author full name is not showing in the converted pdf instead it will show the abbreviation of the full name.
**input screenshot:**
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/3977b315-5297-4414-a4b0-d2311f696355)
output screenshot:
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/98628dec-3e7b-456f-b438-11a715bf9598)

[https://app.zenhub.com/files/358004325/b2209628-c556-4d78-b014-e9f3c88bb9f5/download](https://app.zenhub.com/files/358004325/b2209628-c556-4d78-b014-e9f3c88bb9f5/download)

[https://app.zenhub.com/files/358004325/8a5e7d12-c956-41c3-9084-fc4447393bfa/download]
(https://app.zenhub.com/files/358004325/8a5e7d12-c956-41c3-9084-fc4447393bfa/download)
cc. @m-prodan @lmullane @abin-aot

**Comment by m-prodan** [comment] 2023-06-27 16:14
Per our discussion last week - this is fine re: initials instead of name showing

**Comment by divyav-aot** [comment] 2023-06-27 16:41
Increasing the effort to 5 including the unit and performance testing.

**Comment by nimya-aot** [comment] 2023-06-29 18:26
@divyav-aot Word document with comments  is missing on pdf stich. Could you please check request EDU-2023-1008 on test?

**Comment by nimya-aot** [comment] 2023-06-29 19:57
@divyav-aot  Sorry, missed the name abbreviation comment above. working good

**Comment by divyav-aot** [comment] 2023-06-29 22:21
This ticket covers only the Notes in excel not the comments. If any comments exists, it will print without the content. 
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/8b64a8f6-6a7e-4957-a00e-374d3a3f3566)
cc. @m-prodan @lmullane @nimya-aot @abin-aot

**Comment by nimya-aot** [comment] 2023-06-29 22:36
Working as expected, so closing the ticket

**Closed by nimya-aot** 2023-06-29 22:36 UTC
Labels: Story
