### ISSUE TITLE
Bug fix - UX of Request Queue

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#200] opened 2021-07-16 18:17 UTC
New requests that come in aren't highlighted per UX. 
Perhaps because it they are still "unopened" in workflow?

### Design Updates to Request Queue:
Expected UX
![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/15ac1c9d-7f4c-4068-9007-6ccd8f6b8d7c)

Changes to be made:
- [x] Spacing of columns needs to be adjusted to better match content spacing and design
- [x] All titles should be able seen in full with adjusted spacing
- [x] Column title and content should line up
- [x] Date should be spelled out as per Expected UX. Time stamp should be removed
- [x] General/Personal - please capitalize
- [x] Assigned To dropdown should be same design as UX Expected - Taken from Material UI
- [x] Current Status, not Current State
- [x] ID # is not incrementally changing
- [x] Remove Drop Shadow from Filter Radio Buttons
- [x] Background color for Unopened request
- [x] Sort request queue based on status

Refer:
#20 and #150

**Comment by m-prodan** [comment] 2021-08-05 23:06
@JHarrietha-AOT - I started QA'ing this one - it looks like they've hit the mark with the UI changes needed (will defer to you on this!), but request queue filtering (generals/personals) appears to be broken now.

**Comment by m-prodan** [comment] 2021-08-06 16:31
@divyav-aot - as discussed at stand-up, request queue filtering on radio buttons (general/personal) no longer appears to be working. Tested and replicated on multiple browsers (Brave, Chrome, Edge)

**Comment by m-prodan** [comment] 2021-08-06 20:37
@divyav-aot - confirmed, filtering is working - thank you!

Will defer to @JHarrietha-AOT prior to closing this ticket, but I am satisfied with changes

**Comment by JHarrietha-AOT** [comment] 2021-08-09 17:12
@divyav-aot just reviewed the bug criteria, my only comment would the the column spacing. 

I think XGOV could be moved further to the right. Which would allow for more spacing between Current Status - Assigned to - Received Date. I also think Applicant Name should have more space, as for testing we are typing in shorter names but in reality applicants could have long names and we would want as much to be viewable as possible

Everything else looks good. @m-prodan let me know what you think of the column spacing comment, and agree with the spacing of the applicant name coloum

**Comment by m-prodan** [comment] 2021-08-09 17:57
@JHarrietha-AOT - I put in a request with a long name to see. Now I probably used too long a name for it to be a realistic scenario. But I see what you mean now, someone with a longer last name might get cut-off and if we can salvage some extra space it would make sense to add it to the applicant name to help mitigate that issue.

Looking at it again, I definitely see what you mean with the column spacing. Shall we send it back with comments?

**Comment by JHarrietha-AOT** [comment] 2021-08-09 17:59
@divyav-aot how long do you think updating the columns will take?

**Comment by divyav-aot** [comment] 2021-08-09 18:28
@JHarrietha-AOT - I just updated the spacing. now pushing the changes to dev. once tested will push to test.

**Comment by lmullane** [comment] 2021-08-09 18:58
Thanks, @divyav-aot

**Comment by JHarrietha-AOT** [comment] 2021-08-09 19:01
Thanks @divyav-aot so fast. Let me know when its ready in test and I'll have a look

**Comment by divyav-aot** [comment] 2021-08-09 19:37
@JHarrietha-AOT  - the changes are pushed to test.

**Comment by JHarrietha-AOT** [comment] 2021-08-09 19:49
@divyav-aot Changes look great, thanks for making this update so quickly! I will close this bug ticket with the approved final change.

**Closed by JHarrietha-AOT** 2021-08-09 19:49 UTC
Labels: bug
