### ISSUE TITLE
Request view - updated received date for holiday and late requests not saved in DB

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#2308] opened 2022-06-09 22:31 UTC
**Describe the bug in current situation**
Request view (IAO), if a request is received in weekend or holiday, the received date will be changed to the following business day. This rule also applies to requests received after 5pm in a working day.

The issue is that the request view only applies the rule on front end. The updated received date is not saved in database.

Shall we also apply the same rule in the Angular app?

**Link bug to the User Story**

**Impact of this bug**
This bug or tech debt currently impacts advanced search. 

**Chance of Occurring (high/medium/low/very low)**
low

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
all env

**Steps to Reproduce**
1. Submit request in weekend, holiday or after business hour
2. Go to Advanced Search
3. Click on Received Date
4. Select From and To the business day following that day

**Actual/ observed behaviour/ results**
Cannot find the request in the list

**Expected behaviour**
The request should should show

**Screenshots/ Visual Reference/ Source**

**Comment by lmullane** [comment] 2022-06-20 18:41
@richard-aot,  could you update this ticket with the bug template? Not sure what is the issue is or the expected behaviour.

**Comment by richard-aot** [comment] 2022-06-22 23:51
#2185, #2192 and #2308 are the same issue

**Comment by lmullane** [comment] 2022-06-28 17:36
Duplicate of #2185

**Closed by lmullane** 2022-06-28 17:36 UTC
Labels: bug, Tech Debt
