### ISSUE TITLE
UX Assurance: Left nav bar wrong colour during ministry CFR

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1916] opened 2022-04-19 18:54 UTC
**Describe the bug in current situation**
When I logon as a ministry user (specifically LBR in this case) and open a request that is in the CFR stage, where the CFR is overdue the left nav bar displays as a red-orange. It should be displaying as pink
![image.png](https://images.zenhubusercontent.com/6075c1c3fd068000c09b3e0a/b36a5142-958c-4e67-9fdf-d6a6ef0c0a00)

**Impact of this bug**
I have seen this multiple times but have not tested extensively enough to know if it's just some ministry users, all ministry users, or all users (including IAO). Also haven't tested whether the colour is dependent on the timeliness/overdue status of records.

It doesn't appear to impact functionality from what I can see, but will be confusing for users who are used to the colour coding of states

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Request must have CFR in the overdue state

**Steps to Reproduce**
1. Go to any request in Call for Records, when the call for records is overdue
2. See Banner colour Change

Expected Behaviour:
- No colour change to left hand nav bar when CFR or LDD is overdue

**Comment by mpilchar** [comment] 2022-04-19 18:54
cc: @JHarrietha-AOT

**Comment by aparna-aot** [comment] 2022-04-19 22:59
@mpilchar I can see that the Record is late by 13 days and that is the reason for the red color of the left nav bar and is potentially not a bug. @JHarrietha-AOT can confirm. Thanks!

**Comment by mpilchar** [comment] 2022-04-19 23:08
@aparna-aot I should have mentioned that I ran this by @JHarrietha-AOT before drafting the bug ticket. She confirmed there shouldn't be colour coding in the bar for the overdue status of the selected state. If the call for records were late then it would show in the negative in the text at the bottom

**Comment by divyav-aot** [comment] 2022-04-20 15:14
@mpilchar @JHarrietha-AOT the red color shows based on #452 user story.

**Comment by JHarrietha-AOT** [comment] 2022-04-20 15:25
@divyav-aot Thanks for flagging this. Maybe we discuss it at stand-up today. Personally I am not a fan of it and did not include this in any designs.

**Comment by JHarrietha-AOT** [comment] 2022-04-22 17:15
@m-prodan This is how it is in the design, what do you think of following this with the idea that numbers go into the negative

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/7e4d73f4-d872-4af4-9aac-bca7df1214d2)

**Comment by m-prodan** [comment] 2022-04-22 19:18
Yes - that would be consistent with how remaining days is shown. I will update the expected behaviour for the bug ticket now

**Comment by m-prodan** [comment] 2022-04-22 19:23
Actually @JHarrietha-AOT - have a look at how it looks in the app right now when a request is overdue:

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/44741c28-72a0-47ee-8b4a-63dac3b4e3fa)

It looks like we don't use a negative value for an overdue LDD anyways

**Comment by m-prodan** [comment] 2022-04-22 19:25
I think we have a ticket in our backlog addressing that format already - see #945 - should we just limit this to the colour change?

**Comment by JHarrietha-AOT** [comment] 2022-04-22 19:50
@m-prodan Sounds good, lets just limit this ticket to the colour change

**Comment by m-prodan** [comment] 2022-04-22 19:57
@divyav-aot  @nkan-aot @aparna-aot - from refinement this morning, we are scoping this ticket to just the colour change. The wording/UI of the banner and counters are already addressed in another bug/enhancement ticket

**Comment by lmullane** [comment] 2022-05-11 23:26
Thanks for tackling this one, Nick.

<img width="554" alt="Screen Shot 2022-05-11 at 4 24 34 PM" src="https://user-images.githubusercontent.com/12040839/167963384-4f2503cb-2abe-4acb-84e5-566197729ffa.png">

**Closed by lmullane** 2022-05-11 23:26 UTC
Labels: bug, UX, medium priority
