### ISSUE TITLE
Requests not assigned to my team showing in 'My Team Queue'

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1980] opened 2022-04-26 23:57 UTC
![Screen Shot 2022-04-26 at 4.54.42 PM.png](https://images.zenhubusercontent.com/571e6eb3bf93871ccd9a03d4/7d05558d-e93e-43b8-bd24-02ab73188896)**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. As an Intake User, go to 'My Team's Requests' queue
4. See error (i.e., requests assigned to other teams, such as Flex)

**Actual/ observed behaviour/ results**

**Expected behaviour**
An Intake User should only see requests in the following state not including unopened ![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/66137e76-5b69-44fe-89d9-c78052a59624)

plus any other requests explicitly assigned to intake team

as per spread sheet from issue #761 Intake should see general requests in open state, but not personal requests in open state

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by mpilchar** [comment] 2022-04-27 17:16
Per sprint planning discussion - check this against permissions and please write up expected behaviour

**Comment by m-prodan** [comment] 2022-05-06 20:27
So there is far less requests now showing in 'My Team Requests' as an Intake user - but I note that I can still see all open requests that have been assigned away to flex team - specifically general requests.

Having that said - I think this does meet the expected behaviour - we have it so that "Open" general requests will still be visible in the Intake Team queue - technically these requests won't be in the 'Open' state very long. Let me know your thoughts on this @lmullane before I close this.

**Comment by m-prodan** [comment] 2022-05-11 19:08
@lmullane I think it is because we originally set this up with our first cut of a plan when we originally had correspondence and email in scope of the release. By keeping open general requests in the intake team queue, it allowed the request to stay in Intake's line of sight so that the team lead can peer review the letter. Since personals are managed by the processing team, we set it up so that personals wouldn't show in the intake queue after they opened the request since the processing team largely manages the intake functions

Once we scoped out correspondence and came up with the auto-assign, I am guessing we forgot to revist the original logic and never really caught it because most requests go from open to call for records fairly quickly, especially during our early days of testing, when we had a smaller volume of requests in play.

**Comment by lmullane** [comment] 2022-05-11 22:28
Cool. In training with Intake we were using the 'Assigned to' function for peer review without a state change.

We can close this ticket, but let's confirm with Intake whether they want open, general requests to persist in their team queue.

**Comment by m-prodan** [comment] 2022-05-11 22:31
Sounds good - I'll follow up with Dan - closing ticket.

**Closed by m-prodan** 2022-05-11 22:31 UTC
Labels: bug
