### ISSUE TITLE
Comments - Colored Icons for all Users

### ISSUE THREAD

**Issue by KaraBeach** [bcgov/foi-flow#2437] opened 2022-07-07 21:28 UTC
* As any user ( Ministry or IAO analyst)
* I want to better see the comments from different users
* so that it is easier to differentiate between all comments and users

**Assumptions & Scope**	
What are the assumptions for this story?

* Use existing hex color palette that Jackie has set up in the system at 50 opacity.
* User will be given a random color from the pallete when they make an account.
* User initials will be surrounded by the random color when they post a comment 

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Comment stamped with a color**
* GIVEN I am any user ( Ministry or IAO)
* WHEN I post a comment 
* THEN the color that is assigned to my profile will appear in around my initials

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813726

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by KaraBeach** [comment] 2022-07-07 21:28
@m-prodan, for your review

**Comment by arielleandrews** [comment] 2022-07-08 21:59
Duplicate of #1183

**Closed by arielleandrews** 2022-07-08 21:59 UTC
Labels: Story
