### ISSUE TITLE
No correspondence log after payment done , after grace period

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3201] opened 2022-12-16 17:06 UTC
**Describe the bug in current situation**
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/ac45fabd-32c2-4f16-8c27-539006be6ec3)

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/f2d8bc15-99d4-4b58-95c4-06c161485365)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by divyav-aot** [comment] 2022-12-22 20:05
**Deployment Note**
1. foi-fee-payment WF changes. bpm tagging is needed
2. Migration of existing instances to the new version

**Comment by KyEggleston** [comment] 2022-12-22 23:21
@m-prodan @liseandtea 

I tested this bug / fix, and just want to run some thoughts/questions by you (@liseandtea we already chatted about it, so maybe make sure I didn't miss anything). 

If I recall correctly, this bug was when Katrina made a payment (deposit) for a request, but did not receive/was not sent a Fee Estimate Payment email, nor was the Fee Estimate Payment email posted to the _Contact Applicant_ tab. I think the assumption was that this may have been due to the fees due grace period having elapsed (i.e., payment was not made after 20 business days). 

Katrina was able to pay a deposit after the fees grace period had elapsed on the request (indicated by the comment in the _Comments_ tab stating: "Fees were due to be paid by mm/dd/yyyy, you may consider closing this request as abandoned" .

So a few things to confirm:

- When the fees due grace period has elapsed on a request, and no payment has been made, would the request always be changed to abandoned by the IAO analyst? 
- If yes to the above, should the ability for an applicant to pay their initial deposit or fees (through the "Pay Online" hyperlink in the Fees Estimate Due email) be disabled after the fees due grace period has passed (because the request is assumed to be abandoned)?

Another scenario/question about when there is an outstanding balance:

- When an applicant has paid the initial deposit, and the request has an outstanding balance due at the 'Response' stage , when the request is changed to 'On Hold' to collect the outstanding balance, what happens if the applicant doesn't pay their outstanding fees? Do we contact the applicant after a specified amount of time? Does this ever happen or is it a real edge case?

<h3>Below are some details to replicate the situation/issue that Katrina encountered</h3>

**Assumptions**
That applicants should be able to pay their fee estimate through the "Pay Online" hyperlink in the Fees Estimate Due email even after the fees due grace period (20 business days) has elapsed. If this is not true, you can disregard this section, and we need to make sure that applicants cannot pay after the fees due grace period (which Katrina was able to). 

**Preconditions**
Must be in the TEST environment
Must be logged in as an IAO analyst (IAO analyst role)
Must have an email address in the 'Email' field in the _Request_ tab
Must be on a request that has initial fees (estimate) due (i.e., BalanceRemaining >0)
Must be on a record that has passed the initial fees due grace period, and a comment has been posted in the 'Request History Comments' log, under the _Comments_ tab, stating: "Fees were due to be paid by mm/dd/yyyy, you may consider closing this request as abandoned"

**Steps to Reproduce**
Assuming the preconditions are met:
1. Go to the _Contact Applicant_ tab, and view the most recent Fee Estimate Due email.
2. Click the "Pay Online" hyperlink in the message
3. Go through the payment process and pay the full amount

**Result** 
After making the payment, I correctly received a 'Payment Successful' screen, advising me that I will receive an email regarding my request. However, no Fee Estimate Payment email was sent to and/or received by the applicant (to my email address on the request), and no Fee Estimate Payment email was posted in the _Contact Applicant_ tab.

**Expected Result**
After making a payment, the applicant sees a 'Payment Successful' screen, advising them that they will receive an email regarding the request. The applicant is then sent, and receives, a Fee Estimate Payment email to their email address on the request, and the email is posted in the _Contact Applicant_ tab.

**Comment by m-prodan** [comment] 2022-12-22 23:30
Good questions @KyEggleston to answer:

When the fees due grace period has elapsed on a request, and no payment has been made, would the request always be changed to abandoned by the IAO analyst?

Answer: not always - if there is ongoing communication between the analyst and the applicant, and there is work to narrow the request, we may keep the request on hold until it is resolved. We only close it as abandoned if the applicant has made no effort to contact us, after 20 business days has passed. 

That should also imply my answer for your follow up bullet point, namely that its possible an applicant may end up paying after the grace period, so we consciously allow payment, so long as the request remains in the "on hold" state.

And lastly re: outstanding balance - yes, that would be a real edge case. It would be rare for an applicant to choose to not pay the outstanding balance, after they've paid the deposit. That said, we've had cases before (though quite rare) where that isn't the case and we would close as abandoned. We typically make more of an effort to get in touch with the applicant though, since we have technically completed the request by that point. If the applicant gets in touch with us later, after we close it - what might happen is we would re-open the request and re-issue the outstanding fee again so we can release the package. Again, this would be a very rare edge case.

**Comment by KyEggleston** [comment] 2022-12-22 23:42
Awesome, thanks @m-prodan 

So it sounds like applicants that make a fees estimate payment/deposit, regardless of whether the fees due grace period has elapsed or not, should still be sent a Fee Estimate Payment email to their email address on the request, and the email should also be posted in the _Contact Applicant_ tab. This wasn't occurring for Katrina, so I'll confirm again this isn't happening, and then update this ticket.

**Comment by liseandtea** [comment] 2022-12-23 16:09
I think the crux of the situation is the differences between the applicant paying the initial fee estimate (whether deposit or in full) versus paying the balance due. One has a legislated timeframe and one doesn't so the parameters are not the same.

**Comment by KyEggleston** [comment] 2022-12-23 17:58
Thanks @divyav-aot 

I tested on EDU-2022-12161506, EDU-2022-26699, EDU-2022-45876 whether the fees estimate payment/deposit emails were being sent to applicants after they paid, where the request was past the fees due grace period. 

I can confirm that the emails are now being sent, and are also posted in the _Contact Applicant_ tab. So I believe this is resolved. 

Move to Ready for Prod?

**Comment by divyav-aot** [comment] 2022-12-23 17:59
Thanks @KyEggleston . Yes please move to "Ready for Prod".

**Closed** 2023-01-03 19:01 UTC
Labels: bug, high priority
