### ISSUE TITLE
Stuck after Zero CFR Estimate send for IAO review 

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3128] opened 2022-11-30 03:59 UTC
**Describe the bug in current situation**
If a ministry coordinator created a CFR Fee Form and Send for IAO review and/or unknowingly changed status to Fee estimate with "ZERO ESTIMATED AMOUNT / BALANCE" (like only electronic estimate !)  , then request will fall into a "Limbo" 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to request in Call for records as MInistry User
2. Create a CFR form with only "Electronic records Estimate" . or with any zero balance estimate and Save.
3.  Change request state to Fee estimate. So by default system will make it 'IAO Review in progress"
4. System stays in Limbo - No further edits possible nor to create a new CFR form

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment] 2023-05-29 18:07
Closing, as this is a duplicate of #3749 (which is estimated, and captured possible resolution options)

**Closed by KyEggleston** 2023-05-29 18:07 UTC
Labels: bug, medium priority
