### ISSUE TITLE
View Restricted request on queue

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3021] opened 2022-11-09 16:58 UTC
* As the Intake Manager or Ministry Manager
* I want to see restricted requests clearly marked on my requests queue 
* so that I can track and find restricted requests*

* As the assignee or watcher of a restricted request
* I want to see restricted requests clearly marked on my requests queue or my watching queue
* so that I can track and find restricted requests

**Assumptions & Scope**	
What are the assumptions for this story?
Unless they are the Intake or Ministry Manager, only those assigned or watching a request can see restricted requests on their queue

A restricted request can be assigned or watched by any IAO team member regardless of which ministry it is. For example an EDU request could be assigned to a Central Team manager and analyst.

Restricted requests will never appear on a Team Queue for any user.

Will need to create a Keycloak group for the Intake Manager as they can view all restricted requests regardless of whether or not they are assigned or watching the request.

Ministry Managers can see all restricted requests for their ministry only, regardless of whether or not they are an assignee or a watcher.

What is IN scope?

What is NOT in scope?
Flagging a restricted request #2982
Assigning a restricted request #2983
Comments and tagging #2985
Notifications #2988
Reporting #2984

**Acceptance Criteria**	

**Scenario 1: View restricted requests on assignee 'My Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Requests' queue
* THEN they will see only restricted requests that they are the assignee
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 2: Restricted request 'Watching Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'Watching Requests' queue
* THEN they will see only restricted requests that they are a watcher
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 3: Search restricted requests on 'My Requests' queue**
* GIVEN an assignee of a restricted request (ministry coordinator, IAO analyst, processing team manager) is on their 'My Requests' queue
* WHEN they enter 'restricted' in the search bar  
* THEN the queue will filter to show only assigned restricted requests
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 4: Search restricted requests on 'Watching Requests' queue**
* GIVEN a watcher of a restricted request (ministry coordinator, IAO analyst, processing team manager) is on their 'Watching Requests' queue
* WHEN they enter 'restricted' in the search bar  
* THEN the queue will filter to show only watched restricted requests
* AND each restricted requests will have an 'R' icon in the row
* AND the applicant name will not appear; instead it was say restricted

**Scenario 5: No restricted requests on assignee 'My Requests' queue**
* GIVEN a user is not an assignee of any restricted requests (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Requests' queue
* THEN they will NOT see any restricted requests

**Scenario 6: No restricted requests on 'Watching Requests' queue**
* GIVEN a user is not an watcher of any restricted requests (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'Watching Requests' queue
* THEN they will NOT see any restricted requests

**Scenario 7: Not assigned or watching - no restricted requests on 'My Team' queue**
* GIVEN a user is NOT an assignee or watcher of a restricted request (ministry coordinator, IAO analyst, processing team manager)
* WHEN they are on their 'My Team' queue
* THEN they will NOT see any restricted requests

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/975255940

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2022-11-09 18:33
@m-prodan, @liseandtea, @abin-aot, please review and comment.

**Comment by lmullane** [comment] 2022-11-14 16:55
@abin-aot, did we have an estimate for this story?

cc @m-prodan

**Comment by liseandtea** [comment] 2022-11-15 23:28
@lmullane  looks good except I have questions around "AND the applicant name will not appear; instead it was say restricted" once a restricted file is assigned to a manager/analyst/FOI coordinator. Is this just for the lists only but when you click into the request you see all of the applicant's information?

**Comment by lmullane** [comment] 2022-11-30 19:44
@liseandtea, that is correct, @liseandtea. Concern is if an assignee was sharing their screen of their queue they may inadvertently show the applicant name.

@abin-aot, we will need an estimate on this.

**Comment by lmullane** [comment] 2022-12-08 21:30
@liseandtea, as discussed, an assignee or watcher will be able see all of the applicant details. The name of the applicant will only not appear on the queue.

**Comment by m-prodan** [comment] 2022-12-30 16:37
@abin-aot - confirmed with Arielle, no need for us to change the queue logic so she can see all restricted requests on "my requests" even if she is not assigned. Having a separate search filter for the Intake manager would be helpful, so I will write up a separate user story for that, and will update the AC for this one.

cc: @lmullane

**Comment by m-prodan** [comment] 2022-12-30 16:40
I think all I had to do to address this was remove the first AC - it should be good now @abin-aot

**Comment by abin-aot** [comment] 2022-12-30 17:00
Thanks @m-prodan  , Also Could you please make this story to deal with only InTake manager ? Since the story prior(#2982) to this for flagging request was related with IAO/Intake only!

**Comment by m-prodan** [comment] 2023-01-03 17:15
Note for testing: need to test again for when Ministry flagging is complete - this will only work for IAO right now

**Comment by KyEggleston** [comment] 2023-01-26 23:57
@lmullane @m-prodan @liseandtea 

For Scenario 7, the AC reads:

GIVEN a user is an assignee or watcher of a restricted request (ministry coordinator, IAO analyst, processing team manager)
WHEN they are on their 'My Team' queue
THEN they will NOT see any restricted requests

However, the system currently functions as follows:

GIVEN a user is an assignee or watcher of a restricted request 
WHEN the user is on the 'My Team' queue
THEN they WILL see any restricted requests currently assigned to them
AND they will NOT see any restricted requests that they are not assigned

The current AC for Scenario 7 says that the user should not see ANY restricted requests in the 'My Team' queue, even if they are assigned the restricted request. 

Can you just confirm whether it's fine for a user to only see the restricted requests that they are assigned in the 'My Team' queue, or if they should really not see ANY restricted requests in the 'My Team' queue (and instead, should only see their assigned restricted requests in the 'My Requests' queue.

**Comment by m-prodan** [comment] 2023-01-27 00:07
@KyEggleston - apologies,  I discussed that with @richard-aot and @aparna-aot and confirmed with Arielle that we didn't need that extra layer of protection, since the queue will already just show it as restricted.

As long as ONLY the assigned users can see it in my teams requests, and not anyone else on the team, then it should be fine. I will remove that scenario now.

**Comment by aparna-aot** [comment] 2023-01-27 00:08
@KyEggleston I remember me and @richard-aot had a conversation with @m-prodan regarding the same scenario and confirmed the existing behavior of  showing restricted requests on the team queue if they are assigned to that request. I believe we missed to update that scenario.

**Comment by aparna-aot** [comment] 2023-01-27 00:10
Thanks @m-prodan for the quick reply :)

**Comment by KyEggleston** [comment] 2023-01-30 16:41
Thanks @m-prodan and @aparna-aot!

**Closed by KyEggleston** 2023-01-30 16:41 UTC
Labels: Story
