### ISSUE TITLE
8.0 Findings Task

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4188] opened 2023-07-24 20:47 UTC
DOD
- [ ]  Migration script to de active unused groups

Refer: https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4167

**Comment by divyav-aot** [comment] 2023-07-26 19:03
duplicate of #4201 hence closing this

**Closed by divyav-aot** 2023-07-26 19:03 UTC
Labels: duplicate
