### ISSUE TITLE
Keep duplicate records that are attachments

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3744] opened 2023-05-02 20:43 UTC
* As an IAO analyst
* I want records that are duplicates and attached to an email retained
* so that I can evaluate whether the email content means the record should be released or withheld.

**Assumptions & Scope**	
What are the assumptions for this story?

In general, we want to remove duplicates from the records package. 

However, all duplicate records that are attached to an email should be kept as part of the Records Package. As the context of whether or not a record is attached to an email matters. 

All duplicates attached to all emails should be included in the Records Package.

For example, a record that is a contract may be released. But a contract that is attached to an email from a solicitor would be withheld. It is important for that we do not remove the standalone version of the contract that would be disclosed and then redact the attached version of the contract.

Analysts can review attachments and flag them as Duplicate in the Records Review app if they deem they are indeed duplicates.

What is IN scope?

Exclude all attachments from deduplication.

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Exclude all attachments from deduplication**
* GIVEN an a record (i.e. an email) is uploaded into the Records Log
* WHEN the record has attachments
* THEN the attachments should not be deduplicated
* AND the attachments should be kept in the Records Package
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2023-05-02 20:46
@m-prodan, @abin-aot, @divyav-aot 

A discussion with the business highlighted a new requirement - to retain duplicates attached to emails. The context of the email may change how the record is handled.

**Comment by abin-aot** [comment] 2023-05-05 19:21
@lmullane : I would like to discuss this scenario over test-marshal on real usecase!

**Comment by m-prodan** [comment] 2023-05-10 17:25
Note - removing from release 7.0 - will add shortly thereafter

**Comment by divyav-aot** [comment] 2023-05-19 20:29
increasing the effort to 8 as there are some changes needed from the docreviewer side

**Comment by KyEggleston** [comment] 2023-05-31 17:45
A couple things to note through testing (EDU-2022-00083):

- On attachments in the Records tab, the ellipsis shows 'Download Replaced' available for each attachment, even when there were not replaced. This doesn't occur for the same file that was uploaded, but is not an attachment. Should this be showing up? 

![image](https://github.com/bcgov/foi-flow/assets/117312323/a6b7fb86-6b38-4737-840c-4e8a2a7a6c4a)

![image](https://github.com/bcgov/foi-flow/assets/117312323/d5e81f66-8287-4af4-982d-ad3874ce16b9)

- When we upload duplicate email files (e.g., MSG), which contain the same attachments, do we want to retain the parent email file AND the attachments (i.e., not mark them as duplicates?) Currently, when this happens the system marks the parent email file as a duplicate, but keep the attachments (even if they are duplicates). 

![image](https://github.com/bcgov/foi-flow/assets/117312323/5252392a-55e0-4c5d-b0dc-90e1342426bb)

- In this ticket I think we missed the Harms Package component when refining, and how these changes will affect the Harms Package. For example, look at the files in the image below for this division. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/d5330c64-8be4-4a5c-abe8-03251b0af156)

In the Harms Package, the following files are included, sorted by modified date:

![image](https://github.com/bcgov/foi-flow/assets/117312323/98dab239-7e47-4b48-976f-f039db782be9)

However, I believe we also want to retain the duplicate attachments (e.g., those attachments under _Policy Summary.msg_). 

In addition, _Policy Summary.msg_ is marked as a duplicate, but it is stitched into the Harms Package.

@lmullane @m-prodan @liseandtea - think we may want to chat about some of the above.

**Comment by KyEggleston** [comment] 2023-05-31 17:54
@divyav-aot - perhaps the first bullet point, regarding the 'Download Replaced', can get looked into while the other comments are discussed further?

**Comment by divyav-aot** [comment] 2023-05-31 19:47
@KyEggleston looks like "Download replaced" is a production bug. Created separate bug ticket for the same. cc. @abin-aot 
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3875
I am currently looking into the Harms package issue.

**Comment by abin-aot** [comment] 2023-05-31 20:12
Yes, I can take that issue @KyEggleston , Thanks @divyav-aot

**Comment by KyEggleston** [comment] 2023-05-31 20:18
Thanks @abin-aot and @divyav-aot!

**Comment by KyEggleston** [comment] 2023-06-01 17:51
Note from stand-up:

1. @divyav-aot - When a parent email file is uploaded to the Records tab, and it is a duplicate of another parent email file, the duplicate parent email file, and it's attachments, should be marked as duplicates (as they are, essentially, complete duplicates of one another). When marked as duplicates, the divisional tag for the duplicates should be appended to the original attachment (which was not removed through deduplication). 

So in the image below, the duplicate parent file, and all its attachments, uploaded with the 'System and Liaison and Supports' divisional tag, should be marked as duplicates. All the original files should have the 'System and Liaison and Supports' divisional tag appended to the original files (so they show up in both divisions harms). 

![image](https://github.com/bcgov/foi-flow/assets/117312323/d95c36da-7226-4ddb-8450-2aec77b43fba)

2. If a parent email file is uploaded to the Records tab, and it **_is not_** a duplicate of another parent email file, but they have "duplicate" attachments, the parent email files, and the attachments, should all be retained (not duplicates), and part of the harms package. However, we need to unpack this from the business side, as it can get messy. So hold off on this @divyav-aot 

cc: @lmullane @m-prodan @sumathi-thirumani-aot

**Comment by divyav-aot** [comment] 2023-06-01 18:29
As discussed if a duplicate email with attachment is part of another email attachment, then will treat that as not duplicate. see the screenshot below.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/0156a722-dc9c-42b9-9854-b090e1e16d38)
@m-prodan @KyEggleston @lmullane  @sumathi-thirumani-aot

**Comment by lmullane** [comment] 2023-06-15 16:40
@KyEggleston, please hold on QA until this fix is in TEST not just TEST Marshal.

@divyav-aot will let you know.

**Comment by divyav-aot** [comment] 2023-06-15 19:59
Just a note @m-prodan @KyEggleston  @lmullane As discussed earlier, below case is correct as part of this ticket. Attachments inside a msg will be deduplicated. 
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/f3077c0e-d2bf-4775-a873-541605b39a1e)

**Comment by divyav-aot** [comment] 2023-06-15 20:31
We noticed one edge case, which is already happening in production related to replace attachment. Below example, we replaced TREE1.docx and TREE2.docx with DOCX1.PDF. Ideally one of the attachment should show as duplicate. But the duplicate check is not happening for replaced attachments. Due to this, harms package will have duplicate data of (DOCX1.PDF).
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/78b6eebc-60cd-4441-b0e4-1989c50323a1)
Below is the harms package with duplicate data.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/a5ab057f-8863-4cbc-a49d-0d55feedf604)
[https://app.zenhub.com/files/358004325/9a0b716f-6f6a-4ca9-80a1-490ccd4ef818/download](https://app.zenhub.com/files/358004325/9a0b716f-6f6a-4ca9-80a1-490ccd4ef818/download)

**Comment by abin-aot** [comment] 2023-06-15 20:41
we might need to handle this 'replace attachment - dedupe issue` separately!

**Comment by divyav-aot** [comment] 2023-06-16 17:03
Bug ticket reference: https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3954

**Comment by m-prodan** [comment] 2023-06-22 16:07
closing as released to prod last night

**Closed by m-prodan** 2023-06-22 16:07 UTC
Labels: Story
