### ISSUE TITLE
Notification and comment when applicant has not paid processing fees within 20 days

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#1627] opened 2022-03-03 18:43 UTC
* As an IAO user or ministry coordinator
* I want a notification when an applicant has not paid a processing fee
* so that I know when I can close the request as 'Abandoned'

**Assumptions & Scope**	
What are the assumptions for this story?
Given a request is on hold for a fee payment
When the applicant has not paid the fee within 20 days
Then the IAO analyst should get a notice that the fee has not been paid.

Need PayBC in place so we can capture the payment status for the request to trigger the automated notification.

What is IN scope?
Notifications and comments when a fee is not paid in the 20 days..

What is NOT in scope?
Notifications and comments when a fee is paid.

**Acceptance Criteria**	

**Scenario 1: Notification that fee has not been paid**
* GIVEN a request has been put on hold for fees
* WHEN 20 business days has passed from the date the request is on hold
* THEN all assigned users will receive a notification stating: "Fees were due to be paid by DATE, you may consider closing the request as abandoned"
* AND DATE in the notification shall be the 20th business day after the request was placed on hold

**Scenario 2: Comment that fee has not been paid**
* GIVEN a request has been put on hold for fees
* WHEN 20 business days has passed from the date the request is on hold
* THEN a comment will be posted in the comment log for the request: "Fees were due to be paid by DATE, you may consider closing the request as abandoned"
* AND DATE in the comment shall be the 20th business day after the request was placed on hold

**Scenario 3: Fee Paid in part or whole**
* GIVEN a request has been put on hold for fees
* WHEN the fee estimate has been paid in part or in full
* THEN the notification and comment from scenario 1 and 2 will NOT be triggered

...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment] 2022-07-07 22:46
@lmullane - saw this one near the top of new issues, took a run at it. Let me know if it works for you or if you wanted to include other scenarios/assumptions

**Comment by JHarrietha-AOT** [comment] 2022-08-22 17:00
@divyav-aot This passes UX Assurance, feel free to move to the next column when you're ready.

**Comment by lmullane** [comment] 2022-08-25 18:37
@divyav-aot, will this story also cover notifications for an outstanding fee (i.e. the applicant has paid a deposit)?

Happy to write a new story if required.

cc @m-prodan

**Comment by divyav-aot** [comment] 2022-08-25 19:37
@lmullane - this should be covering for outstanding as well if the text is same for notification/comment.
cc @sumathi-thirumani-aot

**Comment by lmullane** [comment] 2022-08-25 19:52
Thanks for the confirmation, @divyav-aot

**Comment by m-prodan** [comment] 2022-09-06 18:57
@lmullane - I have JER-2022-59672 as being on hold as of Aug 29 - this puts 20 business days at or around September 26th. I've also flagged 20 calendar days to do a check in case the wrong logic was put in. Not sure I have any that I put on hold farther back then that though

**Comment by m-prodan** [comment] 2022-09-26 15:42
20 days has finally passed! Confirming the notification works - however, there is an issue with the notification itself. 

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/fe1fc1ad-e470-4e1a-8b5b-046d666f2807)

Today is September 26th - but the notification references the wrong date. I note that the system generated comment does include the correct date.

cc: @divyav-aot

**Comment by divyav-aot** [comment] 2022-09-26 15:53
Thanks @m-prodan . We will look into this issue and get back to you.

**Comment by m-prodan** [comment] 2022-09-29 17:00
Hi @divyav-aot - I logged into test Marshall, and just noticing that it looks like I get daily notifications, and it is also creating system generated comments daily. This should be expected behaviour. Shall I write up a bug ticket for it? Should I write a bug ticket for both that and the notification text being wrong?

**Comment by m-prodan** [comment] 2022-10-04 23:07
Bug ticket #2892 has been created to address the repeating notifications/comments. Closing ticket!

**Closed by m-prodan** 2022-10-04 23:07 UTC
Labels: Story, marshal
