### ISSUE TITLE
'Save As' - Unable to Select Page Range

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4373] opened 2023-09-01 21:03 UTC
**Describe the bug in current situation**
This was identified on Aug 31 before the pilot user session, where we were testing exporting a consult package.

Since we won't be developing all the consultation functionality for Release 9.0, the plan is to have users produce a package for consultation by using the OOTB 'Save As' function. However, they are unable to use 'Specify Pages' to only select pages from the larger package to export and send for consultation.

This will impact the ability of users to produce a consultation package.

**Link bug to the User Story**

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test-Marshal

**Steps to Reproduce**

On a request with >=2 pages, Select 'Save As'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDFoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d1116106520eddbd27ec4db42e382d942e36c161/image.png)

Enter pages, a page range, or combination, which isn't "1"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUJoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cec58b9b97d710f9b2df8b5b3e8e6adb6f31b994/image.png)

See error, where it says you can only select "1"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDloIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e413599e0b33f0f88116d74695ab7fecb325e316/image.png)

**Actual/ observed behaviour/ results**

Cannot enter pages, or a page range, in the Specify Pages' field.

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

GIVEN a package was >=2 pages
AND the user is in the 'Save As' modal
WHEN a user enters pages, or a page range, in the 'Specify Pages' field that are within the page range of the package
THEN the pages or page range is accepted 
AND when saved, the download will only include those pages, and page ranges, entered

**Comment by lmullane** [comment] 2023-09-06 16:33
Duplicate of #4343

**Closed by lmullane** 2023-09-06 16:33 UTC
Labels: bug
