### ISSUE TITLE
Start date recalculation after fee payment

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2721] opened 2022-08-26 22:44 UTC
**Describe the bug in current situation**
When the applicant successfully pays the fee deposit and the request moves from On Hold to Call for Records, the start date on the request details page is resetting to the date of that state change.

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**
Medium. Only seems to occur with fee payments but occurs every time this scenario. Does not appear to occur when manually changing state from On Hold to Call for Records.

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test marshal environment

**Steps to Reproduce**
1. Go to a request in Fee Estimate state
2. Note the Start Date
3. Change state to On Hold
4. Go through applicant payment process and complete payment
5. Refresh request in test-marshal
6. See Start Date has changed

**Actual/ observed behaviour/ results**
Start date should not change; it should always reflect the date the request was first moved to Open

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
See request #EDU-2022-22111 in test-marshal. The start date was originally the same as the received date but updated to the date the change from On Hold to Call for Records happened after the successful payment.
![image.png](https://images.zenhubusercontent.com/608206453965c51946fdcabf/dbb64e4c-d4a9-4350-bbb1-8da988082617)

**Comment by arielleandrews** [comment] 2022-08-26 22:45
@sumathi-thirumani-aot @divyav-aot I had this bug occur in testing this afternoon. Let me know if you have questions!

**Comment by m-prodan** [comment] 2022-09-15 18:48
Notes for testing:
Request - EDU-2022-113355 - will place on hold today for fee
Will action payment tomorrow to take off hold.

**Comment by m-prodan** [comment] 2022-09-16 15:43
Steps were followed - start date looks to be preserved - however, possibly a new bug has been introduced? The new legislated due date is the same as the original. Since the request was on hold for at least a day, the LDD should have changed. FYI @divyav-aot - I can write up new ticket, or we can fix it as part of this one?

**Comment by divyav-aot** [comment] 2022-09-16 17:02
@m-prodan - I tried one request with onholddays = 5 in dev-marshal. The due date is getting updated properly for this request.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/267738fd-a8d3-4c28-b71b-e51ed4029a1f)
Could you please share the requestId from test-marshal? I can quickly check the BE.

**Comment by divyav-aot** [comment] 2022-09-16 19:07
Hi @m-prodan, I can see that the above request due date is not updated.  Somehow I am not able to reproduce this issue in local. Could you please create a separate ticket for the same. Meantime I will keep 1 request in dev-marshal and test-marshal to monitor this issue.

**Comment by divyav-aot** [comment] 2022-09-20 16:55
Hi @m-prodan , I tried again with different option looks like the due date is getting calculated. Could you please try again and let me know the steps to reproduce the issue.
requeststatusid = 11 (On Hold)
requeststatusid = 2 (Call For Records)
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/d8906f98-7731-4ef3-ad00-f2541211e4c7)

**Comment by m-prodan** [comment] 2022-09-22 21:22
Late on this - will close this one and write up bug ticket for LDD not calculating properly after on hold

**Closed by m-prodan** 2022-09-22 21:22 UTC
Labels: bug, high priority, marshal
