### ISSUE TITLE
PDFTron Client Side stitching to enable comprehensive search on all Redactable documents

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3907] opened 2023-06-06 18:18 UTC
Title of ticket: 

#### Description
As per the analysis done on #3852 and as explained during POC demo , we are taking 3 approaches to solve requirements for  `global` search on content, comments, print, preview . First - Client Side stitch  on documents using PDFTron API, second - Server side stitching , similar to what we have on Harms download. Third - A hybrid option between first(Client side stitching) and second(server side stitching). Based on the analysis , it is easy to do a client side stitching and use PDFTRON features, than do a server side stitching, since server side stitching has its own down side as mentioned on comments, and demo on #3852

So the plan is to start with **_Client Side stitching approach first_**, since it will cover vast majority of Requests and its Records package , which has less documents/small - medium records. Also, we need to find the maximum threshold of documents/pages/size which we can comfortably work with client side stitching 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Review POC on  https://github.com/bcgov/foi-docreviewer/commit/c428a134439be5c8b47f489ae4d278fa9d971074
- [x]  Develop the logic for Client Side stitching based on the array of document as per the sort logic
- [x]  Confirm existing functionalities for RECORDS review is intact with Client Side stitching approach - Left panel, page flagging, Annotations saving, Replace Records/attachments etc. 
- [ ]  Threshold finding - Maximum # of records, pages, size that this option can handle. 
- [x]  Any rework , if required.
- [x] Merge to Marshal branch on FOI-Docreviewer.

**Comment by abin-aot** [comment] 2023-06-06 18:19
@m-prodan - this is the first task to do the client side stitching

**Comment by aparna-aot** [comment] 2023-06-28 21:43
**Adding some of the existing issues/observations(Unrelated to client side stitching):**
- Scrolling through pages won't be reflected on the left panel page numbers. (ie., the page scrolled through won't be highlighted on the left panel).
- Full page Redaction bug by PDFTRON : While using multi page redaction tool if we specifies a page range over 10 (i.e. 1-15) the first 10 pages are not redacted. (No response abt the fix so far by the support team).
- As mentioned during the standup on 2023-06-26 - While using "full page redactions for specific pages" feature, users should specify the stitched document's page numbers(and not individual document's pageno.). As per discussion we might have to either bring up a new design or have to display the stitched page numbers on the left panel.

**Regarding load testing:**
Before pushing the updates to dev/test environments, tested the feature in local for about **17** documents with a total of **3374** pages and also added **2756** annotations.
Observation : No significant issues or slowness in terms of loading documents and annotations.
Total size of the annotation(XML) fetching API was 2.0MB.

![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/5d08a825-109a-492b-a7d5-1c12e60231a0)
![image.png](https://images.zenhubusercontent.com/61a7e1d68c56cdce5dc09fd8/a9359798-f881-4815-ab43-96c7258ea2e1)

**Comment by lmullane** [comment] 2023-07-05 16:57
Testing this story will require full regression of page flags, redactions, etc.

**Comment by m-prodan** [comment] 2023-07-05 17:02
Also note for QA - try adding or removing documents to see what the corresponding behaviour. Annotations/redactions in PDF Tron are page/location based, see if removing pages shifts redactions

**Comment by aparna-aot** [comment] 2023-07-06 17:28
Just saw some issues with annotations in test-marshal env(couldn't reproduce in my local with the same branch). Currently investigating the issue and will move back to Ready for QA once its fixed.

**Comment by aparna-aot** [comment] 2023-07-07 00:07
Issue was some code was missing . Fixed now & is ready for QA.

**Comment by aparna-aot** [comment] 2023-07-11 16:36
Just an update to the above comment : #3907 is already in test-marshal, we are just waiting for #3812 to be shipped to test-marshal for doing a full regression.

**Comment by nimya-aot** [comment] 2023-07-20 21:14
File upload is not working on test-marshal. Will test once its ready

**Comment by nimya-aot** [comment] 2023-07-23 22:17
working as expected, so closing it

**Comment by nimya-aot** [comment] 2023-07-24 19:34
Needs to test threshold (maximum number of pages handling) as team requested. so moving back to QA

**Comment by nimya-aot** [comment] 2023-07-24 22:49
@aparna-aot will continue testing once portfolio issue merged on test-marshal

**Comment by nimya-aot** [comment] 2023-08-02 15:27
If the records package has image, incompatible files etc ,then search option is not working , Needs to test  after fixing everything

**Comment by nimya-aot** [comment] 2023-08-08 16:50
Tested global search up to 11k pages on redaction app. But didn't find the threshold, may be needs to find it in future if business required it

**Closed by nimya-aot** 2023-08-08 16:50 UTC
Labels: Task, dev, marshal
