### ISSUE TITLE
Issues found in Marshal

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#3069] opened 2022-11-19 01:34 UTC
Title of ticket: 

#### Description
- [ ] The payonline page is transparent when connected to vpn. 
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/4b2ab8cf-14ef-4d9b-bf69-8abdd297acfe)

- [x]  Attachment log search is not working for certain requests. 
**Solution/Explanation**
Request EDO-2015-50102 in dev-marshal - search for "fee" keyword in the attachment list. The dummy file also shows. This is because the category for the file is feeassessed-onhold but the tag shows "Applicant" in the log. This is because of the requirement mentioned in #2470 Scenario 4

- [x] The divisional stage add/update comments are not generating.
**Solution/Explanation**
One entry in CommentTypes table was missing in marshals. Related to migration scripts arrangement issue in marshals. This should not happen in dev/test.

- [x] "(ask for Information Access Operations)" text in footer in  the footer of email and receipts.
**Solution/Explanation**
Remove "(ask for Information Access Operations)" text from the footer as per #2413 ticket

- [x] red dot for new comments to the left of the username is not showing.
**Solution/Explanation**
It was merge issue. The code was not merged to marshals

- [x] Contact applicant - manual state change to Response
1. Send outstanding pay email through contact applicant
2. Applicant pay the amount
3. IAO see only below states in the state dropdown
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/36064813-1cd9-4c48-a512-e0a88c5725cc)
Do we need to add response also part of the state dropdown?

**Solution/Explanation**
As discussed in Teams, we will address this as part of #2960 ticket

- [x] Logo not appearing in applicant email/preview email

**Solution/Explanation**
This is because of the LAN restrictions given to the foi-flow application. The logo was accessing from foi-flow application. Now the logo link is replaced with formsflowai.web logo.

- [x] 2 WF instance IDs are getting created in request-processing WF

**Solution/Explanation**
Instead of passing the foiRequestID, it was using ministryRequestID. This has been corrected.

**Comment by abin-aot** [comment] 2022-11-19 23:07
@divyav-aot , @nkan-aot  I found the root cause of this issue. This issue is related with BC GOV network restrictions and/or not allowing not satisfying SSL certs on below mentioned CDN endpoints. Solution is to make those artifacts as part of our build rather than following formsflows idea of referring CDN resources.
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/c43d1a30-09d1-4a51-b80e-0967b937fdc1)

**Comment by divyav-aot** [comment] 2022-11-21 23:43
1. FOI FE changes
2. Email Template Update in S3
3. Receipt hash code change in BE DB

**Comment by abin-aot** [comment] 2022-12-01 00:22
Closing this task as discussed, Refer this task for Business QA. https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/bcgov/foi-flow/3135

**Closed by abin-aot** 2022-12-01 00:22 UTC
Labels: Task
