### ISSUE TITLE
Filtering Attachments

### ISSUE THREAD

**Issue by arielleandrews** [bcgov/foi-flow#2470] opened 2022-07-18 20:18 UTC
* As a user (all users)
* I want to filter the attachments listed in the attachments tab 
* so that I can more easily find the attachments I need 

**Assumptions & Scope**	
* Filters will be based on the badges applied to attachments
* Only one filter can be applied at a time
* Users can toggle between filters the same way they can toggle between filters in the Comments section
* Applicant filter will only be visible for IAO users, not Ministry users
* All new tags will not be associated with any state changes, they are for attachments uploaded by users to the attachments tab directly

What is IN scope?

What is NOT in scope?
* Searching attachments. This is covered in user story #1974

**Acceptance Criteria**	

**Scenario 1: Default filter set to All**
* GIVEN I am a user
* WHEN I navigate to the Attachments tab 
* THEN the default filter will be set to All 

**Scenario 2: Select other filter**
* GIVEN I am a user on the Attachments tab
* WHEN I select a filter other than All (General, Applicant, Extensions) 
* THEN the attachments displayed will filter based on the badge that corresponds to the filter 

**Scenario 3: Applicant filter not visible for Ministry users**
* GIVEN I am a Ministry user
* WHEN I navigate to the the Attachments tab
* THEN the only filters visible to me will be General, Extensions, and All
* AND the default filter will be set to All

**Scenario 4: Update to Fee Assessed-On Hold tag**
* GIVEN an IAO user uploads an attachment in the state change modal from Fee Estimate to On Hold
* WHEN they hit Save
* THEN the attachment will have the "Applicant" tag in the attachment tab

**Scenario 5: Update to CFR-Fee Assessed tag**
* GIVEN a Ministry user uploads an attachment in the state change modal from CFR to Fee Estimate
* WHEN they hit Save
* THEN the attachment will have the "CFR-Fee Estimate" tag in the attachment tab

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813727
https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/817813733

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by arielleandrews** [comment] 2022-07-20 20:37
@JHarrietha-AOT will assign colour codes to new tags

**Comment by JHarrietha-AOT** [comment] 2022-07-20 21:57
Updated colours @aparna-aot @arielleandrews (Let me know if you have any questions, or if any tags were missed)

![image.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/86959bdd-25ba-408a-bb16-6b6051af1d64
)

**Comment by richard-aot** [comment] 2022-08-11 16:32
This feature is deployed to dev environment.
Scenario 4 is not applicable to dev/test environment. Fee Estimate to On Hold attachment is only available in dev-marshal/test-marshal, so it will be ready for testing after I merge the feature to dev-marshal. Will add another comment after the merge.

**Comment by JHarrietha-AOT** [comment] 2022-08-11 17:23
Just posting here that #2489 has not been completed yet so we are unable to add attachment that correspond with all the tags listed above and unable to test that. We should makes sure it is in the upcoming sprint @arielleandrews @m-prodan. So that the update for attachments is complete

**Comment by JHarrietha-AOT** [comment] 2022-08-11 17:26
@richard-aot I have the same UX Assurance comment that I had for @abin-aot  with the search bar in comments.

There is way to much extra white space around the filters. The "Search Attachments" section should have an increased width to fix this.

This is what it looks like now: ![Screen Shot 2022-08-11 at 1.21.13 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/a2514635-1c67-44ff-a54f-00aeb93add75)
This is what the spacing should look like![Screen Shot 2022-08-11 at 1.25.45 PM.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/19b436e2-08f8-4468-acf5-2258420f9043)

Let me know if this this something small you can fix now or if this is something you would like a separate UX Assurance ticket for

**Comment by richard-aot** [comment] 2022-08-11 19:37
@JHarrietha-AOT the width issue is fixed. Please verify. Thanks.

**Comment by JHarrietha-AOT** [comment] 2022-08-11 20:20
Passed UX Assurance Thanks for the Quick Changes @abin-aot & @richard-aot

**Comment by m-prodan** [comment] 2022-08-23 21:55
Most scenarios passed, but am unable to test scenario 4 -  awaiting branch merge to test marshal so I can test scenario 4 there.

**Comment by m-prodan** [comment] 2022-08-23 23:05
@lmullane - discussed with Richard, the merge to marshal likely won't happen until next week. Shall we just extract scenario 4 into its own story? It seems like it should have been separated out because of the requirements. I will bring it up at our business stand up in the morning. This ticket is ready to be closed otherwise

**Comment by lmullane** [comment] 2022-08-23 23:23
@m-prodan, I'm open to that approach. Let's discuss tomorrow.

**Comment by m-prodan** [comment] 2022-08-24 16:18
Per discussion at stand up - I've created a task to QA 2470 again in Marshal when the branch is merged so I can confirm scenario 4 functions as expected. All other scenarios passed

**Closed by m-prodan** 2022-08-24 16:18 UTC
Labels: Story
