### ISSUE TITLE
Notification and comments for completion of records removal and conversion

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3119] opened 2022-11-29 17:23 UTC
* As a ministry coordinator and IAO analyst
* I want a notification and comment on when dedupe and file conversion is complete
* so that I know when I can update the request state or review the files

**Assumptions & Scope**	
What are the assumptions for this story?
If there is a large batch of records uploaded, removing duplicate records and converting records to PDF may take some time.

The ministry coordinator will want to be notified when these actions are complete, for example, when they wish to change the state request. Even if they were the one who completed the action they should be notified when it is finished.

IAO analysts may want to be notified in case they want to review records early.

As the Gathering Records log (number of file deduplicated, etc) will be updated, 

User will want an audit log of who uploaded records and when posted as comments in the Comments log.

What is IN scope?
Notifications for the assignees and watchers that dedupe and file conversion is complete.

For rank 1 dedupe.

What is NOT in scope?
Dedupe and file conversion is covered in #3120

**Acceptance Criteria**	

**Scenario 1: Assignee notification**
* GIVEN a ministry coordinator or IAO analyst is assigned to the request
* AND the ministry coordinator has uploaded records
* WHEN the records removal and conversion is complete
* THEN the assignee will receive a notification: "A batch of records has been uploaded by USERNAME"

**Scenario 2: Assignee notification**
* GIVEN a ministry coordinator or IAO analyst is watcher for a request
* AND the ministry coordinator has uploaded records
* WHEN the records removal and conversion is complete
* THEN the watcher will receive a notification: "A batch of records has been uploaded by USERNAME"

...
**Scenario 3:  Comment of upload**
* GIVEN a ministry coordinator or analyst has uploaded records
* WHEN the records removal and conversion is complete
* THEN the comment will be posted in the Request History: "A batch of records has been uploaded by USERNAME" on (date and time)"

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by lmullane** [comment] 2022-11-30 18:52
@abin-aot., @JHarrietha-AOT, please review for accuracy.

cc @m-prodan, @KyEggleston

**Comment by m-prodan** [comment] 2022-11-30 22:29
Unless there is a seperate user story to address this - I suspect we'll be asked to have a comment posted in request history when upload of records is completed by a user. I just note it says a comment won't be necessary, but I think Ministry users will want to ensure there's a record on file of when they uploaded records.

**Comment by JHarrietha-AOT** [comment] 2022-12-01 16:32
@m-prodan Would it be better to just send a notification to the Ministry users when the batch they have uploaded on X Date, has completed.

Realistically Ministry users will likely upload them to our system in batches as they receive then from divisions. Instead of one lump sum, this will help push them through deduplication and file conversion and give IAO the opportunity to start working on any records that have completed the process and are ready to review. We also know records can be added at any time in a request, so I almost think it could be apart of training for Ministry users to add a comment tagging the IAO Analyst when they have received all records that they expect to, and will reach out if they add any more to the Gather Records Log.

**Comment by lmullane** [comment] 2022-12-05 20:15
@m-prodan, I have updated the assumptions and added an AC for a comment each time the upload of a batch of records has been finished (i.e., records are converted and duplicates removed).

Do we need a time stamp for the notification or only the comment?

@JHarrietha-AOT, I updated the message in the notification to say a batch has been uploaded, and removed the 'complete' so there is not confusion that all the records are now there. 

Let me know if the language make sense?

**Comment by m-prodan** [comment] 2022-12-06 16:22
Yes I think just noting it as a successful upload of a batch of records should suffice, as I agree with @JHarrietha-AOT - Ministry users will likely upload as they receive records, not all at once. When they switch to records review or harms assessment should be the signal that their gathering has concluded.

**Comment by sumathi-thirumani-aot** [comment] 2022-12-16 17:31
Technical Discussion
Questions:
1. "records removal"  - Dedupe ?
2. Comment and notification message is not related to the event. Need new wording.
**Estimate - 21**
Implementation approach (HLD)
1. Two/more tables(Conversion, Dedupe) for mapping batch, request# and file count, FilePath services related.
2. Background Service / CRONJOB  - reconciliation 
 -- This background service will talk with 2 DB, Service will re-conciliation on Dedupe/DocReview DB and push data to notification, Comment table on FOI FLOW

**Comment by lmullane** [comment] 2022-12-16 18:51
Need to confirm that the backend is not covered in #3120. 21 seems a high estimate for the notification and believe the backend should be covered in the other ticket.

@sumathi-thirumani-aot to confirm.

**Comment by sumathi-thirumani-aot** [comment] 2023-02-03 19:44
@m-prodan  The feature is deployed in test-marshal.

**Comment by KyEggleston** [comment] 2023-02-03 21:41
@sumathi-thirumani-aot - thanks for working on this.

One thing I noticed - in the assumptions, and in Scenario 1, I believe the expectation is that the ministry coordinator assigned to the request (i.e., the user in the 'Ministry Assigned To' field) is also notified when the batch is uploaded successfully. 

However, currently the ministry coordinator in the 'Ministry Assigned To' field is **_not_** notified when a batch is uploaded. 

Scenario 1 could perhaps have been more clear, as it just says: "...the _**assignee**_ will receive a notification...". It would have been more accurate to say the "assignees", and both the users in the 'IAO Assigned To' and 'Ministry Assigned To' should be notified. 

Let me know if you need any clarification - otherwise, everything else is working. 

I tested on EDU-2023-05858 in Test-Marshal.

**Comment by sumathi-thirumani-aot** [comment] 2023-02-04 01:35
The notifications are designed to go both assignees and watchers (excluding the action doer). 
Verified in dev-marshal; working as expected. We can connect on it. 

IAO Assignee:
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/08dc6c0d-ff0e-4179-b98b-b972cfa27c13)![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/beabb986-a437-4534-8be6-4b7398c11ad
Ministry Assignee:
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/a7a74ef2-56e6-4804-a489-b49abffeebfe)

Ministry Action Doer:
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/29124532-e29f-4664-8b0a-08e3e9272c60)

**Comment by m-prodan** [comment] 2023-02-06 17:31
Per discussion at stand-up - moving back to review, as in this particular case, the person that takes the action should also get the notification, as noted in assumptions/scenario 1

**Comment by KyEggleston** [comment] 2023-02-07 18:27
Confirmed the batch upload notification is being sent to the action-doer when they are also assigned the request in the 'Ministry Assigned To' field. This will ensure the ministry coordinator assigned to the request is notified when a batch upload is complete on the request, even when they are the batch uploader.

**Closed by KyEggleston** 2023-02-07 18:27 UTC
Labels: Story
