### ISSUE TITLE
UX Update : Additional Data Inputs required for Personal Requests related with MCFD

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2861] opened 2022-09-28 21:19 UTC
* As an applicant who submits Personal Request using Public FOI Request Submission
* I want,  six Additional Record Type Options to appear  when I select option "Yourself"
 (only!)  on "Who are you requesting records about?" screen
* so that Personals IAO Team can reduce their Document gathering, review processes based on the additional information gathered from applicant.
* These six new multi-select additional options can be clubbed together based on the request. 

**Assumptions & Scope**	
What are the assumptions for this story?

What is IN scope?  
 Only Personal Requests related with MCFD will have this flow

What is NOT in scope? 
 Other General Requests and/or Other ministries Applicant Experience

**Acceptance Criteria**	

**Scenario 1: Requesting records about "Yourself"*
* GIVEN ... when an applicant creates a personal request and
* WHEN ... applicant is on "Who are you requesting records about?" screen , which displays 3 options/checkbox - "Yourself" , " A child under 12 years old" and "Another person"
* THEN ... if applicant selects(only!) option "Yourself" , she/he will be able to see 6 additional new multi-select options/check boxes on the "What kind of records are looking for?" screen.  They are as per below image. Previously these were radio buttons or single select options and existing option "Child protection and youth care"  and  "Adoption" is removed/replaced with these 6 new multi select options
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/d888d695-2b9a-455f-8e1d-dbbef6584c6d)

**Scenario 2: Alert Section on "What kinds of records are you looking for" **
* GIVEN ... While an applicant creates a personal request 
* WHEN ... on "What kinds of records are you looking for" screen based on the pre-conditions like "requesting records" for "YourSelf" - refer Scenario1 
* THEN ... an alert section should appear which indicates the applicant about the types of records which is NOT catered by IAO / FOI Request services . Similar to image image
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/6b946cbb-9139-459c-94de-43d1a569ac2e)

**Scenario 3: Additional Screen for  "Your records from an adoption**
* GIVEN ... the applicant has  selected "Your records from an adoption"  on "What kinds of records are you looking for" screen
* WHEN ... clicked "continue" button
* THEN... a new screen should appear for the applicant to select sub options as per below screen
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/d10bb8d0-0368-41fc-8100-5388858c74ef)

**Scenario 4: Additional Screen for  "Your records as a child in a child protection investigation**
* GIVEN ... the applicant has  selected "Your records as a child in a child protection investigation" on "What kinds of records are you looking for" screen
* WHEN ... clicked "continue" button
* THEN... a new screen should appear for the applicant to select sub options as per below screen
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/56d10632-d68d-43ec-a174-9d3cd6a2721b)

**Scenario 5: Additional Screens for  "Your records as a parent in a child protection investigation" , "Your records as a foster parent", "Your records as a child in youth care"**
* GIVEN ... the applicant has  selected "Your records as a parent in a child protection investigation" and/or "Your records as a foster parent" and/or "Your records as a child in youth care" and/or "Your records as a parent of a child in youth care" on "What kinds of records are you looking for" screen
* WHEN ... clicked "continue" button
* THEN... a new screens should appear for the applicant to select sub options as per below screen
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/57182bee-dcc6-45b7-984f-25ba2518ef1f)

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/aafe5379-9119-4ecb-ba3d-a36e32bd603f)

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/3f81b65e-181d-4e3d-92a7-9b73e80d815c)

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/6960b338-0594-48c1-a4b7-a3fdd1b83595)

**Scenario 6: All new six additional multi-select options can or cannot be combined with each other**
* GIVEN ... the applicant is "What kinds of records are you looking for" screen and selects additional new options in combination of 1 or 2 or 3 or 4 or 5 or 6
* WHEN ... and clicked "continue" button
* THEN... a new screens should appear to the applicant  based on the selections. and if none of these new options are selected then these screens should not appear. 

**Scenario 7: Sub option's children display is conditional**
* GIVEN ... the applicant is on any of this new "record type" screen 
* WHEN ... and when screen gets loaded with main sub options only., child options should not be visible
* THEN...  when applicant selects any sub option its children should be displayed.  Refer below images
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/e72b30ae-ae4a-47cb-8095-ad6748747d62)
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/e91515a9-5658-4708-b395-7338ac8b3de2)

**Scenario 8:  Info box on FOI request description if any of the new Record Type option is selected**
* GIVEN ... the applicant has selected any of this new record type option 
* WHEN ... and while navigating through different screens and on the FOI request Description screen
* THEN...  an Info box should appear above the description text box indicating the need for the applicant to enter additional information , if any  - Refer below image
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/b8fe0bdd-5ae0-4c6b-8319-b68519926d14)
...

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment] 2022-10-05 16:06
Note: do full regression when QA'ing (test all scenarios for angular form)

**Comment by abin-aot** [comment] 2022-10-18 04:17
@lmullane , @m-prodan  , @JHarrietha-AOT  - ACs updated - Please have a look!

**Comment by JHarrietha-AOT** [comment] 2022-10-18 17:16
@m-prodan this looks good to. Just wondering if you would prefer the content being written out for future testing purposes or if its okay that it's screenshots. Let me know

**Comment by m-prodan** [comment] 2022-10-21 15:28
Hi all - looks good, I've been testing various scenarios, emails are working fine and form is working fine.

Quick question though - should this not be: "Investigation of your parent when you were a child"

![image.png](https://images.zenhubusercontent.com/6081a4c82f0c363dddb9c1a0/8a51e559-ae6d-4497-9258-6bc6d224788c)


I didn't see the original designs, so I assume this is a typo? cc: @JHarrietha-AOT @abin-aot

**Comment by JHarrietha-AOT** [comment] 2022-10-21 15:39
@m-prodan It is a spelling mistake, we caught this yesterday when reviewing with Intake and MCFD along with a series of other small text changes. These changes should be done today and pushed to test

**Comment by m-prodan** [comment] 2022-10-21 23:28
Functionally - all works as expected now, and spelling error flagged has since been corrected. Closing ticket - nice work @abin-aot

**Closed by m-prodan** 2022-10-21 23:28 UTC
Labels: Story
