### ISSUE TITLE
Records - Cleanup

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#4268] opened 2023-08-15 16:30 UTC
DOD
====
- [x] Remove the dependency on recordformats.json for displaying the record list
- [x] recordformats.json should be only used for upload purpose
- [x] Record API to update the property "isredactionready" to be true only if the record will be redacted. (currently it is true only for all converted/deduped files and incompatible files. Not updating this flag as it is used in foi-flow and doc reviewer for many cases)
- [x] Record API to include new property "isconverted" and/or "convertedfilename"
- [x] Remove dependency of recordformats.json for harms download

**Comment by divyav-aot** [comment] 2023-09-14 20:57
The changes are pushed to test environment. Please a normal regression on records upload(different types including portfolios), replace (including attachment) and all download options.

**Comment by m-prodan** [comment] 2023-09-19 00:41
@nimya-aot - not sure if you are getting this error, and unsure root of the ticket. While trying to QA the download inactive story, I went to records and would consistently get a "unable to save your request now, try again in a few minutes" and the records tab is unable to upload records. Screenshots on 2 different requests with dev console, it looks like the link is referencing test marshal which might be why this is happening:
cc: @divyav-aot @Aman-Hundal 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjZ2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e93ba9adbff2f71fe4c46d59b1d1668d0bc61710/Error%201.PNG)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcit2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ec494f3dcd3969257cea32e70cbf5d87db93c2c9/error%202.PNG)

**Comment by nimya-aot** [comment] 2023-09-19 15:57
@m-prodan I got the red toast message on the records tab. But the records were visible for me.

**Comment by divyav-aot** [comment] 2023-09-19 16:28
@m-prodan I am not facing this issue. I tried with different browsers. I am able to upload files for above mentioned requests. Could you please check again and confirm.

**Comment by m-prodan** [comment] 2023-09-20 18:29
had the issue again initially, but cache clear resolved. I assume my constant changing of profiles and document uploads might make for QA challenges related to the records tasks

**Comment by nimya-aot** [comment] 2023-09-20 18:40
Division stages were missing on a newly created request. But started working after a refresh. May be we need to keep an eye on this behaviour.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlc5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e17495d501652d9c871cb71579e0c8d7e78e3cfe/image.png)

**Comment by divyav-aot** [comment] 2023-09-20 19:29
Thanks @m-prodan for the update. 
@nimya-aot The issue mentioned above is not related to this ticket. You can create a bug with low priority. We will monitor this.

**Comment by nimya-aot** [comment] 2023-09-20 21:08
@divyav-aot ok, We already have a bug ticket for this issue. I just reopened this .
https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4426

**Comment by nimya-aot** [comment] 2023-09-20 21:31
working good, so closing it

**Closed by nimya-aot** 2023-09-20 21:31 UTC
Labels: bug, Tech Debt, high priority
