### ISSUE TITLE
Download for Harms Stuck as In Progress

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4643] opened 2023-10-26 23:02 UTC
**Describe the bug in current situation**
On TRA-2023-32501 in PROD - the 'Download for Harms' appears to be stuck as in progress. Previously, it was consistently being thrown into error. 

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment] 2023-10-27 00:35
For some unknown reason certain listed is causing extra/irregular high resource consumption, even though package is a normal 16MB package , due to this PDF Stitching POD was getting restarted. ADhoc STEP ,  I increased the resources on normal stitching service to 12GB, then tried again it went through. 
[Uploading... pdftrichingmemory usage for TRA FILE.JPG]

**Comment by abin-aot** [comment] 2023-10-27 23:31
@KyEggleston - confirmed the har,s package download on this PROD request. hence closing

**Closed by abin-aot** 2023-10-27 23:31 UTC
Labels: bug, production
