### ISSUE TITLE
Deployment of Dedupe Computing Set up into OCP

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2836] opened 2022-09-27 03:35 UTC
Title of ticket: 

#### Description
The purpose of this task is to Deploy all Dedupe micro-services to OCP - emerald and/or silver

#### Dependencies
Are there any dependencies?
For Production deployment , we need Emerald Cluster with SDN to be ready( FYI @lmullane ), till then for DEV, TEST we can use existing Silver OCP. ***** In case if Emerald SDN release get delayed from November 2022, then we need to set up on premise deployment . this will be a different effort !!!!! - as informed ***** - this will get decided as we go - OCTOBER 20th.???
cc: @m-prodan 

#### DOD
- [ ] OCP templates for all instances
- [ ] OCP N/W yamls
- [ ]  SDN N/W  set ups, policies,
- [ ]  Communication with existing Silver OCP
- [ ] deployments - DEV, TEST and PRod

**Comment by lmullane** [comment] 2023-01-04 22:18
Duplicate of #3253

**Closed by lmullane** 2023-01-04 22:18 UTC
Labels: devops, Task
